import { makeStyles, shorthands, tokens } from "@fluentui/react-components";

const thinScrollbar = {
	scrollbarWidth: "thin" as const,
	scrollbarColor: `${tokens.colorNeutralForeground3} ${tokens.colorNeutralBackground3}`,
};

export const useRawLogsStyles = makeStyles({
	toolbar: {
		display: "flex",
		alignItems: "center",
		justifyContent: "flex-start",
		flexWrap: "wrap",
		width: "100%",
		...shorthands.gap("8px"),
	},
	count: {
		fontSize: tokens.fontSizeBase100,
		color: tokens.colorNeutralForeground3,
	},
	turnSelect: {
		flex: 1,
		minWidth: 0,
		maxWidth: "260px",
		fontSize: tokens.fontSizeBase200,
		color: tokens.colorNeutralForeground1,
		backgroundColor: tokens.colorNeutralBackground1,
		...shorthands.border("1px", "solid", tokens.colorNeutralStroke1),
		...shorthands.borderRadius(tokens.borderRadiusMedium),
		...shorthands.padding("4px", "8px"),
		cursor: "pointer",
		":disabled": { opacity: 0.6, cursor: "default" },
	},
	refreshButton: {
		minWidth: "auto",
		marginLeft: "auto",
		...shorthands.padding("4px", "10px"),
		...shorthands.border("1px", "solid", tokens.colorNeutralStroke1),
		...shorthands.borderRadius(tokens.borderRadiusMedium),
		backgroundColor: tokens.colorNeutralBackground1,
		color: tokens.colorNeutralForeground1,
		fontSize: tokens.fontSizeBase200,
		cursor: "pointer",
		display: "inline-flex",
		alignItems: "center",
		...shorthands.gap("4px"),
		":hover": { backgroundColor: tokens.colorNeutralBackground1Hover },
		":disabled": { opacity: 0.6, cursor: "default" },
	},
	list: {
		display: "flex",
		flexDirection: "column",
		flex: 1,
		minHeight: 0,
		overflowY: "auto",
		overflowX: "hidden",
		...shorthands.padding("4px", "8px", "12px"),
		...shorthands.gap("8px"),
		...thinScrollbar,
	},
	row: {
		display: "flex",
		flexDirection: "column",
		...shorthands.border("1px", "solid", tokens.colorNeutralStroke2),
		...shorthands.borderRadius(tokens.borderRadiusMedium),
		backgroundColor: tokens.colorNeutralBackground1,
		...shorthands.padding("8px", "10px"),
		...shorthands.gap("4px"),
	},
	header: {
		display: "flex",
		alignItems: "center",
		justifyContent: "space-between",
		...shorthands.gap("8px"),
		width: "100%",
		...shorthands.border("none"),
		...shorthands.padding("0"),
		backgroundColor: "transparent",
		color: "inherit",
		cursor: "pointer",
		textAlign: "left",
		":hover": { opacity: 0.85 },
	},
	chevron: {
		display: "inline-flex",
		alignItems: "center",
		color: tokens.colorNeutralForeground3,
	},
	headerLeft: {
		display: "flex",
		alignItems: "center",
		flexWrap: "wrap",
		...shorthands.gap("6px"),
		minWidth: 0,
	},
	roleBadge: {
		fontSize: tokens.fontSizeBase100,
		fontWeight: tokens.fontWeightSemibold,
		textTransform: "uppercase",
		letterSpacing: "0.4px",
		...shorthands.padding("2px", "6px"),
		...shorthands.borderRadius(tokens.borderRadiusSmall),
		whiteSpace: "nowrap",
	},
	roleUser: {
		backgroundColor: tokens.colorPaletteBlueBackground2,
		color: tokens.colorPaletteBlueForeground2,
	},
	roleAssistant: {
		backgroundColor: tokens.colorPaletteGreenBackground2,
		color: tokens.colorPaletteGreenForeground2,
	},
	roleToolCall: {
		backgroundColor: tokens.colorPaletteLightTealBackground2,
		color: tokens.colorPaletteLightTealForeground2,
	},
	roleToolResult: {
		backgroundColor: tokens.colorPaletteLavenderBackground2,
		color: tokens.colorPaletteLavenderForeground2,
	},
	roleMcpCall: {
		backgroundColor: tokens.colorPaletteMarigoldBackground2,
		color: tokens.colorPaletteMarigoldForeground2,
	},
	roleMcpResult: {
		backgroundColor: tokens.colorPaletteYellowBackground2,
		color: tokens.colorPaletteYellowForeground2,
	},
	roleA2aCall: {
		backgroundColor: tokens.colorPalettePinkBackground2,
		color: tokens.colorPalettePinkForeground2,
	},
	roleA2aResult: {
		backgroundColor: tokens.colorPaletteBerryBackground2,
		color: tokens.colorPaletteBerryForeground2,
	},
	roleError: {
		backgroundColor: tokens.colorPaletteRedBackground2,
		color: tokens.colorPaletteRedForeground2,
	},
	agent: {
		fontSize: tokens.fontSizeBase200,
		fontWeight: tokens.fontWeightSemibold,
		color: tokens.colorNeutralForeground1,
		whiteSpace: "nowrap",
		overflow: "hidden",
		textOverflow: "ellipsis",
	},
	tool: {
		fontFamily: tokens.fontFamilyMonospace,
		fontSize: tokens.fontSizeBase200,
		color: tokens.colorNeutralForeground2,
		whiteSpace: "nowrap",
		overflow: "hidden",
		textOverflow: "ellipsis",
	},
	timestamp: {
		fontSize: tokens.fontSizeBase100,
		color: tokens.colorNeutralForeground3,
		whiteSpace: "nowrap",
	},
	contentWrapper: {
		position: "relative",
		marginTop: "4px",
	},
	content: {
		fontFamily: tokens.fontFamilyMonospace,
		fontSize: tokens.fontSizeBase200,
		color: tokens.colorNeutralForeground1,
		whiteSpace: "pre-wrap",
		wordBreak: "break-word",
		backgroundColor: tokens.colorNeutralBackground3,
		...shorthands.padding("6px", "44px", "6px", "8px"),
		...shorthands.borderRadius(tokens.borderRadiusSmall),
		marginTop: 0,
		marginBottom: 0,
		maxHeight: "240px",
		overflowY: "auto",
		...thinScrollbar,
	},
	copyButton: {
		position: "absolute",
		top: "4px",
		right: "12px",
		minWidth: "26px",
		width: "26px",
		height: "26px",
		...shorthands.padding(0),
		zIndex: 2,
		backgroundColor: tokens.colorNeutralBackground1,
		":hover": {
			backgroundColor: tokens.colorNeutralBackground1Hover,
		},
		"& .fui-Button__icon": {
			fontSize: "16px",
			width: "16px",
			height: "16px",
		},
	},
	emptyState: {
		display: "flex",
		flexDirection: "column",
		alignItems: "center",
		justifyContent: "center",
		flex: 1,
		textAlign: "center",
		...shorthands.padding("24px"),
		...shorthands.gap("4px"),
	},
	emptyTitle: {
		fontSize: tokens.fontSizeBase300,
		fontWeight: tokens.fontWeightSemibold,
		color: tokens.colorNeutralForeground1,
	},
	emptyDescription: {
		fontSize: tokens.fontSizeBase200,
		color: tokens.colorNeutralForeground3,
	},
	loadMoreIndicator: {
		textAlign: "center",
		fontSize: tokens.fontSizeBase100,
		color: tokens.colorNeutralForeground3,
		...shorthands.padding("4px", "0", "8px"),
	},
	subToolbar: {
		display: "none",
	},
	toggle: {
		display: "inline-flex",
		alignItems: "center",
		...shorthands.gap("6px"),
		fontSize: tokens.fontSizeBase200,
		color: tokens.colorNeutralForeground2,
		cursor: "pointer",
		userSelect: "none",
		whiteSpace: "nowrap",
	},
});
