import { makeStyles, shorthands } from "@fluentui/react-components";

export const useVoiceInputStyles = makeStyles({
	root: {
		position: "relative",
		display: "flex",
		alignItems: "center",
		...shorthands.gap("6px"),
	},
	listeningIndicator: {
		position: "absolute",
		right: "0",
		bottom: "calc(100% + 10px)",
		display: "inline-flex",
		alignItems: "center",
		...shorthands.gap("6px"),
		...shorthands.padding("8px", "12px"),
		...shorthands.borderRadius("10px"),
		backgroundColor: "var(--agent-chat-surface)",
		boxShadow: "0 4px 12px rgba(0, 0, 0, 0.12)",
		color: "var(--agent-chat-muted)",
		whiteSpace: "nowrap",
		zIndex: 1,
	},
	listeningDot: {
		width: "8px",
		height: "8px",
		borderRadius: "50%",
		backgroundColor: "#f28b82",
		flexShrink: 0,
	},
	actionButton: {
		minWidth: "34px",
		width: "34px",
		height: "34px",
		...shorthands.borderRadius("50%"),
		...shorthands.padding("0"),
		...shorthands.border("none"),
		backgroundColor: "transparent",
		color: "var(--agent-chat-muted)",
		cursor: "pointer",
		display: "inline-flex",
		alignItems: "center",
		justifyContent: "center",
		":hover": {
			backgroundColor: "var(--agent-chat-hover)",
			color: "var(--agent-chat-fg)",
		},
	},
	actionButtonConfirm: {
		...shorthands.border("1px", "solid", "var(--agent-chat-border)"),
	},
	button: {
		minWidth: "34px",
		width: "34px",
		height: "34px",
		...shorthands.borderRadius("50%"),
		...shorthands.padding("0"),
		...shorthands.border("none"),
		backgroundColor: "transparent",
		color: "var(--agent-chat-muted)",
		cursor: "pointer",
		display: "inline-flex",
		alignItems: "center",
		justifyContent: "center",
		":hover": {
			backgroundColor: "var(--agent-chat-hover)",
			color: "var(--agent-chat-fg)",
		},
	},
	buttonRecording: {
		backgroundColor: "var(--agent-chat-brand)",
		color: "#ffffff",
		":hover": {
			backgroundColor: "var(--agent-chat-brand-hover)",
			color: "#ffffff",
		},
	},
});
