import { makeStyles, shorthands, tokens } from "@fluentui/react-components";

const thinScrollbar = {
	scrollbarWidth: "thin" as const,
	scrollbarColor: `${tokens.colorNeutralForeground3} ${tokens.colorNeutralBackground3}`,
};

export const useConversationHistoryStyles = makeStyles({
	searchWrap: {
		position: "relative",
		width: "100%",
	},
	searchIcon: {
		position: "absolute",
		left: "8px",
		top: "50%",
		transform: "translateY(-50%)",
		color: tokens.colorNeutralForeground3,
		pointerEvents: "none",
	},
	searchInput: {
		width: "100%",
		boxSizing: "border-box",
		...shorthands.padding("6px", "10px", "6px", "28px"),
		...shorthands.border("1px", "solid", tokens.colorNeutralStroke1),
		...shorthands.borderRadius(tokens.borderRadiusMedium),
		fontSize: tokens.fontSizeBase200,
		color: tokens.colorNeutralForeground1,
		backgroundColor: tokens.colorNeutralBackground1,
		outlineStyle: "none",
		fontFamily: "inherit",
		"::placeholder": { color: tokens.colorNeutralForeground4 },
	},
	countText: {
		fontSize: tokens.fontSizeBase100,
		color: tokens.colorNeutralForeground3,
	},
	newChatButton: {
		minWidth: "auto",
		...shorthands.padding("4px", "10px"),
		...shorthands.border("none"),
		...shorthands.borderRadius(tokens.borderRadiusMedium),
		backgroundColor: tokens.colorBrandBackground,
		color: tokens.colorNeutralForegroundOnBrand,
		fontSize: tokens.fontSizeBase200,
		fontWeight: tokens.fontWeightSemibold,
		cursor: "pointer",
		display: "inline-flex",
		alignItems: "center",
		...shorthands.gap("4px"),
		":hover": { backgroundColor: tokens.colorBrandBackgroundHover },
	},
	list: {
		display: "flex",
		flexDirection: "column",
		flex: 1,
		minHeight: 0,
		overflowY: "auto",
		overflowX: "hidden",
		...shorthands.padding("0", "6px", "0", "12px"),
		...thinScrollbar,
	},
	card: {
		display: "flex",
		alignItems: "flex-start",
		justifyContent: "space-between",
		...shorthands.gap("10px"),
		...shorthands.border("none"),
		...shorthands.padding("10px", "2px", "10px", "4px"),
		...shorthands.borderBottom("1px", "solid", tokens.colorNeutralStroke2),
		width: "100%",
		backgroundColor: "transparent",
		textAlign: "left" as const,
		cursor: "pointer",
		outlineStyle: "none",
		fontFamily: "inherit",
		fontSize: "inherit",
		lineHeight: "inherit",
		appearance: "none" as const,
		":hover": { backgroundColor: tokens.colorNeutralBackground1Hover },
		":last-child": { borderBottomStyle: "none" },
	},
	cardContent: { flex: 1, minWidth: 0 },
	cardTitleRow: {
		display: "flex",
		alignItems: "center",
		justifyContent: "space-between",
		...shorthands.gap("10px"),
		width: "100%",
		minWidth: 0,
	},
	cardTitle: {
		fontSize: tokens.fontSizeBase200,
		fontWeight: tokens.fontWeightSemibold,
		color: tokens.colorNeutralForeground1,
		whiteSpace: "nowrap",
		overflow: "hidden",
		textOverflow: "ellipsis",
		flex: 1,
	},
	cardTime: {
		fontSize: tokens.fontSizeBase100,
		color: tokens.colorNeutralForeground3,
		whiteSpace: "nowrap",
		flexShrink: 0,
	},
	emptyState: {
		display: "flex",
		flexDirection: "column",
		alignItems: "center",
		justifyContent: "center",
		textAlign: "center",
		flex: 1,
		...shorthands.padding("32px", "16px"),
	},
	emptyTitle: {
		marginTop: "12px",
		fontSize: tokens.fontSizeBase300,
		fontWeight: tokens.fontWeightSemibold,
		color: tokens.colorNeutralForeground1,
	},
	emptyDescription: {
		maxWidth: "320px",
		marginTop: "6px",
		fontSize: tokens.fontSizeBase200,
		color: tokens.colorNeutralForeground3,
		lineHeight: tokens.lineHeightBase300,
	},
	noService: {
		display: "flex",
		alignItems: "center",
		justifyContent: "center",
		flex: 1,
		color: tokens.colorNeutralForeground3,
		fontSize: tokens.fontSizeBase200,
	},
});
