import { makeStyles, shorthands, tokens } from "@fluentui/react-components";

export const useChatMessageBubbleStyles = makeStyles({
	userBlock: {
		display: "flex",
		flexDirection: "column",
		alignItems: "flex-end",
		...shorthands.gap("2px"),
	},
	userTime: {
		fontSize: tokens.fontSizeBase100,
		color: "var(--agent-chat-muted)",
	},
	userBubble: {
		maxWidth: "86%",
		backgroundColor: "var(--agent-chat-brand)",
		color: "var(--agent-chat-user-fg)",
		...shorthands.padding("10px", "16px"),
		...shorthands.borderRadius("16px", "16px", "4px", "16px"),
		fontSize: tokens.fontSizeBase300,
		lineHeight: tokens.lineHeightBase300,
		fontWeight: tokens.fontWeightRegular,
		overflowWrap: "break-word",
		wordBreak: "break-word",
		boxSizing: "border-box",
	},
	assistantBlock: {
		display: "flex",
		flexDirection: "column",
		alignItems: "flex-start",
		...shorthands.gap("2px"),
	},
	assistantPreamble: {
		display: "flex",
		alignItems: "center",
		...shorthands.gap("8px"),
		color: "var(--agent-chat-muted)",
		fontSize: tokens.fontSizeBase100,
	},
	avatar: {
		width: "32px",
		height: "32px",
		borderRadius: "50%",
		display: "flex",
		alignItems: "center",
		justifyContent: "center",
		backgroundImage: "linear-gradient(135deg, #3367d6 0%, #5f4dd0 100%)",
		color: "#ffffff",
		flexShrink: 0,
	},
	assistantCard: {
		width: "calc(100% - 40px)",
		marginLeft: "40px",
		backgroundColor: "var(--agent-chat-card)",
		...shorthands.border("1px", "solid", "var(--agent-chat-border)"),
		...shorthands.borderRadius("4px", "16px", "16px", "16px"),
		...shorthands.padding("14px", "18px"),
		boxSizing: "border-box",
	},
	assistantBubble: {
		maxWidth: "calc(100% - 40px)",
		marginLeft: "40px",
		backgroundColor: "var(--agent-chat-surface)",
		color: "var(--agent-chat-fg)",
		...shorthands.border("1px", "solid", "var(--agent-chat-border)"),
		...shorthands.borderRadius("4px", "16px", "16px", "16px"),
		...shorthands.padding("10px", "16px"),
		fontSize: tokens.fontSizeBase300,
		lineHeight: tokens.lineHeightBase300,
		whiteSpace: "pre-wrap",
		overflowWrap: "break-word",
		wordBreak: "break-word",
		boxSizing: "border-box",
	},
	errorText: {
		color: "var(--colorPaletteRedForeground1, #c4314b)",
		fontSize: "0.88rem",
	},
	skeletonLine: {
		height: "14px",
		...shorthands.borderRadius("4px"),
		marginBottom: "8px",
		backgroundImage:
			"linear-gradient(90deg, var(--agent-chat-border) 25%, transparent 50%, var(--agent-chat-border) 75%)",
		backgroundSize: "200% 100%",
		animationName: {
			from: { backgroundPositionX: "200%" },
			to: { backgroundPositionX: "-200%" },
		},
		animationDuration: "1.5s",
		animationIterationCount: "infinite",
		animationTimingFunction: "ease-in-out",
	},
	rawDataLabel: {
		margin: "0 0 8px",
		fontSize: "12px",
		opacity: 0.7,
		fontStyle: "italic",
	},
	toolsUsedRow: {
		display: "flex",
		flexWrap: "wrap",
		alignItems: "center",
		...shorthands.gap("6px"),
		marginLeft: "40px",
		marginTop: "4px",
		fontSize: "11px",
		color: "var(--agent-chat-muted)",
	},
	toolsUsedLabel: {
		textTransform: "uppercase",
		letterSpacing: "0.04em",
		fontWeight: tokens.fontWeightSemibold,
		opacity: 0.7,
	},
	toolChip: {
		display: "inline-flex",
		alignItems: "center",
		...shorthands.padding("1px", "8px"),
		...shorthands.borderRadius("10px"),
		...shorthands.border("1px", "solid", "var(--agent-chat-border)"),
		backgroundColor: "var(--agent-chat-surface)",
		fontFamily: tokens.fontFamilyMonospace,
		fontSize: "11px",
	},
	rawDataPre: {
		fontFamily: "inherit",
		fontSize: "13px",
		whiteSpace: "pre-wrap",
		wordBreak: "break-word",
		margin: "0",
		backgroundColor: "rgba(128,128,128,0.08)",
		...shorthands.padding("10px"),
		...shorthands.borderRadius("6px"),
	},
	userHover: {
		position: "relative",
		display: "flex",
		flexDirection: "column",
		alignItems: "flex-end",
		...shorthands.gap("2px"),
		":hover .agent-chat-copy, :focus-within .agent-chat-copy": {
			opacity: 1,
			pointerEvents: "auto",
		},
	},
	assistantHover: {
		position: "relative",
		":hover .agent-chat-copy, :focus-within .agent-chat-copy": {
			opacity: 1,
			pointerEvents: "auto",
		},
	},
	copyButton: {
		opacity: 0,
		pointerEvents: "none",
		transitionProperty: "opacity",
		transitionDuration: "120ms",
		minWidth: "auto",
		height: "24px",
		width: "24px",
		...shorthands.padding("0"),
	},
	copyButtonUser: {
		marginTop: "2px",
		alignSelf: "flex-end",
	},
	copyButtonAssistant: {
		marginLeft: "40px",
		marginTop: "4px",
	},
});
