import { makeStyles, shorthands, tokens } from "@fluentui/react-components";

export const usePageLayoutStyles = makeStyles({
	root: {
		position: "relative",
		display: "flex",
		flexDirection: "column",
		height: "100%",
		minHeight: 0,
		boxSizing: "border-box",
		overflow: "hidden",
		backgroundColor: tokens.colorNeutralBackground1,
	},
	rootSidebar: {
		backgroundColor: tokens.colorNeutralBackground1,
	},
	pageContainer: {
		display: "flex",
		flexDirection: "column",
		flex: 1,
		minHeight: 0,
		width: "100%",
		maxWidth: "980px",
		marginLeft: "auto",
		marginRight: "auto",
		...shorthands.padding("24px", "24px", "0"),
		boxSizing: "border-box",
	},
	pageContainerSidebar: {
		maxWidth: "none",
		marginLeft: "0",
		marginRight: "0",
		height: "100%",
		...shorthands.padding("0"),
	},
	header: {
		display: "flex",
		alignItems: "center",
		justifyContent: "space-between",
		width: "100%",
		flexWrap: "wrap",
		...shorthands.gap("12px"),
	},
	headerSidebar: {
		minHeight: "42px",
		flexWrap: "nowrap",
		...shorthands.padding("0", "12px"),
		...shorthands.borderBottom("1px", "solid", tokens.colorNeutralStroke2),
		backgroundColor: tokens.colorNeutralBackground1,
		boxSizing: "border-box",
		flexShrink: 0,
	},
	headerTitleGroup: {
		minWidth: 0,
		flex: 1,
	},
	headerActions: {
		display: "flex",
		alignItems: "center",
		justifyContent: "flex-end",
		...shorthands.gap("4px"),
		flexShrink: 0,
	},
	headerCloseButton: {
		minWidth: "28px",
		width: "28px",
		height: "28px",
		...shorthands.border("none"),
		...shorthands.borderRadius("50%"),
		...shorthands.padding("0"),
		display: "inline-flex",
		alignItems: "center",
		justifyContent: "center",
		backgroundColor: "transparent",
		color: tokens.colorNeutralForeground3,
		cursor: "pointer",
		flexShrink: 0,
		":hover": {
			backgroundColor: tokens.colorNeutralBackground1Hover,
			color: tokens.colorNeutralForeground1,
		},
	},
	title: {
		fontSize: tokens.fontSizeBase600,
		fontWeight: tokens.fontWeightSemibold,
		color: tokens.colorNeutralForeground1,
		lineHeight: tokens.lineHeightBase600,
	},
	titleSidebar: {
		fontSize: tokens.fontSizeBase300,
		lineHeight: tokens.lineHeightBase300,
		color: tokens.colorNeutralForeground1,
	},
	toolbar: {
		display: "flex",
		flexDirection: "column",
		alignItems: "stretch",
		width: "100%",
		marginTop: "12px",
		marginBottom: "12px",
		...shorthands.gap("12px"),
	},
	toolbarSidebar: {
		marginTop: "0",
		marginBottom: "0",
		...shorthands.padding("8px", "12px", "6px"),
		...shorthands.gap("8px"),
	},
	content: {
		display: "flex",
		flexDirection: "column",
		flex: 1,
		minHeight: 0,
		width: "100%",
		overflow: "hidden",
	},
});
