import { makeStyles, shorthands, tokens } from "@fluentui/react-components";

const thinScrollbarStyles = {
	scrollbarWidth: "thin" as const,
	scrollbarColor: `${tokens.colorNeutralForeground3} ${tokens.colorNeutralBackground3}`,
	"::-webkit-scrollbar": {
		width: "6px",
		height: "6px",
	},
	"::-webkit-scrollbar-track": {
		backgroundColor: tokens.colorNeutralBackground3,
		...shorthands.borderRadius(tokens.borderRadiusCircular),
	},
	"::-webkit-scrollbar-thumb": {
		backgroundColor: tokens.colorNeutralForeground3,
		...shorthands.borderRadius(tokens.borderRadiusCircular),
	},
	"::-webkit-scrollbar-thumb:hover": {
		backgroundColor: tokens.colorNeutralForeground3,
	},
};

export const useTemplatePageStyles = makeStyles({
	toolbarTopRow: {
		display: "flex",
		alignItems: "center",
		width: "100%",
		...shorthands.gap("8px"),
	},
	toolbarTopRowSidebar: {
		flexDirection: "column",
		alignItems: "stretch",
		...shorthands.gap("8px"),
	},
	toolbarFooterRow: {
		display: "flex",
		alignItems: "center",
		justifyContent: "space-between",
		width: "100%",
	},
	searchInput: {
		width: "100%",
		boxSizing: "border-box",
	},
	searchInputSidebar: {
		width: "100%",
		minWidth: 0,
	},
	searchInputField: {
		"::placeholder": {
			color: tokens.colorNeutralForeground4,
		},
	},
	addButton: {
		whiteSpace: "nowrap",
	},
	addButtonSidebar: {
		minWidth: "auto",
	},
	countText: {
		fontSize: tokens.fontSizeBase200,
		color: tokens.colorNeutralForeground3,
		alignSelf: "flex-start",
	},
	countTextSidebar: {
		fontSize: tokens.fontSizeBase100,
	},
	errorBanner: {
		marginBottom: "12px",
		...shorthands.padding("10px", "12px"),
		...shorthands.borderRadius(tokens.borderRadiusMedium),
		backgroundColor: tokens.colorPaletteRedBackground1,
		color: tokens.colorPaletteRedForeground1,
		fontSize: tokens.fontSizeBase200,
		lineHeight: tokens.lineHeightBase200,
	},
	list: {
		display: "flex",
		flexDirection: "column",
		flex: 1,
		minHeight: 0,
		overflowY: "auto",
		overflowX: "hidden",
		...shorthands.borderTop("1px", "solid", tokens.colorNeutralStroke2),
	},
	listSidebar: {
		...shorthands.padding("0", "6px", "0", "12px"),
		borderTopStyle: "none",
		...thinScrollbarStyles,
	},
	templateRow: {
		display: "flex",
		alignItems: "flex-start",
		justifyContent: "space-between",
		...shorthands.gap("16px"),
		...shorthands.padding("18px", "8px"),
		...shorthands.borderBottom("1px", "solid", tokens.colorNeutralStroke2),
		...shorthands.borderRadius(tokens.borderRadiusMedium),
		backgroundColor: "transparent",
		outlineStyle: "none",
	},
	templateRowSidebar: {
		...shorthands.padding("10px", "2px", "10px", "4px"),
		...shorthands.borderRadius("0"),
	},
	templateContent: {
		flex: 1,
		minWidth: 0,
	},
	templateTitleRow: {
		display: "flex",
		alignItems: "center",
		flexWrap: "wrap",
		...shorthands.gap("10px"),
	},
	templateTitle: {
		fontSize: tokens.fontSizeBase300,
		fontWeight: tokens.fontWeightSemibold,
		color: tokens.colorNeutralForeground1,
	},
	templateTitleSidebar: {
		fontSize: tokens.fontSizeBase200,
	},
	agentBadge: {
		display: "inline-flex",
		alignItems: "center",
		...shorthands.padding("2px", "8px"),
		...shorthands.borderRadius(tokens.borderRadiusCircular),
		backgroundColor: tokens.colorBrandBackground2,
		fontSize: tokens.fontSizeBase200,
		color: tokens.colorBrandForeground1,
	},
	agentBadgeSidebar: {
		...shorthands.padding("1px", "6px"),
		fontSize: tokens.fontSizeBase100,
	},
	templateDescription: {
		marginTop: "6px",
		fontSize: tokens.fontSizeBase200,
		color: tokens.colorNeutralForeground3,
		whiteSpace: "nowrap",
		overflow: "hidden",
		textOverflow: "ellipsis",
	},
	templateDescriptionSidebar: {
		marginTop: "4px",
		fontSize: tokens.fontSizeBase100,
	},
	rowActions: {
		display: "flex",
		alignItems: "center",
		...shorthands.gap("4px"),
		flexShrink: 0,
	},
	rowActionsSidebar: {
		...shorthands.gap("8px"),
	},
	iconButton: {
		minWidth: "32px",
	},
	iconButtonSidebar: {
		minWidth: "20px",
		width: "20px",
		height: "20px",
		...shorthands.padding("0"),
	},
	rowActionTooltipTarget: {
		display: "inline-flex",
	},
	loadingState: {
		display: "flex",
		alignItems: "center",
		justifyContent: "center",
		flex: 1,
		minHeight: 0,
	},
	emptyState: {
		display: "flex",
		flexDirection: "column",
		alignItems: "center",
		justifyContent: "center",
		textAlign: "center",
		flex: 1,
		minHeight: 0,
		...shorthands.padding("48px", "24px"),
	},
	emptyIcon: {
		display: "inline-flex",
		alignItems: "center",
		justifyContent: "center",
		width: "56px",
		height: "56px",
		...shorthands.borderRadius(tokens.borderRadiusCircular),
		backgroundColor: tokens.colorNeutralBackground3,
		color: tokens.colorBrandForeground1,
	},
	emptyTitle: {
		marginTop: "16px",
		fontSize: tokens.fontSizeBase400,
		fontWeight: tokens.fontWeightSemibold,
		color: tokens.colorNeutralForeground1,
	},
	emptyDescription: {
		maxWidth: "420px",
		marginTop: "8px",
		fontSize: tokens.fontSizeBase200,
		color: tokens.colorNeutralForeground3,
		lineHeight: tokens.lineHeightBase300,
	},
	emptyAction: {
		marginTop: "20px",
	},
	panelLayer: {
		position: "absolute",
		inset: 0,
		display: "flex",
		justifyContent: "flex-end",
		zIndex: 40,
	},
	panelBackdrop: {
		position: "absolute",
		inset: 0,
		backgroundColor: "rgba(15, 23, 42, 0.18)",
		backdropFilter: "blur(2px)",
	},
	panel: {
		position: "relative",
		display: "flex",
		flexDirection: "column",
		width: "min(620px, 100%)",
		height: "100%",
		backgroundColor: tokens.colorNeutralBackground1,
		boxShadow: tokens.shadow16,
		...shorthands.borderLeft("1px", "solid", tokens.colorNeutralStroke2),
	},
	panelHeader: {
		display: "flex",
		alignItems: "center",
		justifyContent: "space-between",
		...shorthands.gap("12px"),
		...shorthands.padding("12px", "16px"),
		...shorthands.borderBottom("1px", "solid", tokens.colorNeutralStroke2),
	},
	panelTitleGroup: {
		minWidth: 0,
		flex: 1,
	},
	panelTitleRow: {
		display: "flex",
		alignItems: "center",
		...shorthands.gap("8px"),
	},
	panelTitleIcon: {
		color: tokens.colorBrandForeground1,
		fontSize: "20px",
		flexShrink: 0,
	},
	panelTitle: {
		fontSize: tokens.fontSizeBase500,
		fontWeight: tokens.fontWeightSemibold,
		color: tokens.colorNeutralForeground1,
	},
	panelCloseButton: {
		minWidth: "36px",
		width: "36px",
		height: "36px",
		...shorthands.padding("0"),
		...shorthands.border("1px", "solid", tokens.colorNeutralStroke1),
		...shorthands.borderRadius(tokens.borderRadiusMedium),
		backgroundColor: tokens.colorNeutralBackground1,
	},
	panelBody: {
		position: "relative",
		display: "flex",
		flexDirection: "column",
		flex: 1,
		minHeight: 0,
		overflowY: "auto",
		...shorthands.padding("20px", "18px", "24px"),
		...shorthands.gap("18px"),
		...thinScrollbarStyles,
	},
	panelFooter: {
		display: "flex",
		alignItems: "center",
		justifyContent: "flex-start",
		...shorthands.gap("10px"),
		...shorthands.padding("16px"),
		...shorthands.borderTop("1px", "solid", tokens.colorNeutralStroke2),
		backgroundColor: tokens.colorNeutralBackground1,
	},
	panelPrimaryButton: {
		minWidth: "96px",
	},
	panelSecondaryButton: {
		minWidth: "96px",
	},
	panelBusyOverlay: {
		position: "absolute",
		inset: 0,
		display: "flex",
		alignItems: "center",
		justifyContent: "center",
		zIndex: 10,
		backgroundColor: "rgba(255, 255, 255, 0.88)",
		backdropFilter: "blur(2px)",
	},
	panelShimmerOverlay: {
		position: "absolute",
		inset: 0,
		display: "flex",
		flexDirection: "column",
		zIndex: 10,
		backgroundColor: tokens.colorNeutralBackground1,
		...shorthands.padding("20px", "18px", "24px"),
		...shorthands.gap("24px"),
		overflowY: "auto",
		...thinScrollbarStyles,
	},
	formField: {
		display: "flex",
		flexDirection: "column",
		...shorthands.gap("8px"),
	},
	formFieldHeader: {
		display: "flex",
		alignItems: "flex-start",
		...shorthands.gap("12px"),
	},
	formFieldContent: {
		paddingLeft: "36px",
		boxSizing: "border-box",
	},
	fieldIcon: {
		display: "inline-flex",
		alignItems: "center",
		justifyContent: "center",
		width: "24px",
		height: "24px",
		color: tokens.colorBrandForeground1,
		flexShrink: 0,
	},
	fieldTitleGroup: {
		minWidth: 0,
		flex: 1,
	},
	fieldTitle: {
		fontSize: tokens.fontSizeBase300,
		fontWeight: tokens.fontWeightSemibold,
		color: tokens.colorNeutralForeground1,
		lineHeight: tokens.lineHeightBase300,
	},
	fieldDescription: {
		marginTop: "4px",
		fontSize: tokens.fontSizeBase200,
		color: tokens.colorNeutralForeground2,
		lineHeight: tokens.lineHeightBase300,
	},
	fieldInput: {
		width: "100%",
		maxWidth: "100%",
		minWidth: 0,
	},
	contentInput: {
		width: "100%",
		minHeight: "108px",
		fontFamily: 'Consolas, "Courier New", monospace',
		"& textarea": {
			minHeight: "108px",
			fontFamily: 'Consolas, "Courier New", monospace',
			fontSize: tokens.fontSizeBase200,
			lineHeight: tokens.lineHeightBase300,
			boxSizing: "border-box",
			...thinScrollbarStyles,
		},
	},
	dialogContent: {
		display: "flex",
		flexDirection: "column",
		...shorthands.gap("12px"),
	},
	shimmerColumn: {
		display: "flex",
		flexDirection: "column",
		...shorthands.gap("12px"),
	},
	shimmerRow: {
		display: "flex",
		...shorthands.gap("10px"),
		marginTop: "4px",
	},
	shimmerSavingRow: {
		display: "flex",
		alignItems: "center",
		justifyContent: "center",
	},
});
