import { makeStyles, tokens } from "@fluentui/react-components";

export const useTemplateDesignerStyles = makeStyles({
	root: {
		display: "flex",
		flexDirection: "column",
		flex: 1,
		height: "100%",
		width: "100%",
		minHeight: 0,
		backgroundColor: tokens.colorNeutralBackground1,
		borderRadius: tokens.borderRadiusLarge,
		boxShadow: tokens.shadow4,
		overflow: "hidden",
	},
	toolbar: {
		display: "flex",
		alignItems: "center",
		justifyContent: "space-between",
		flexWrap: "wrap",
		gap: tokens.spacingHorizontalS,
		paddingLeft: tokens.spacingHorizontalL,
		paddingRight: tokens.spacingHorizontalL,
		paddingTop: tokens.spacingVerticalS,
		paddingBottom: tokens.spacingVerticalS,
		borderBottomWidth: "1px",
		borderBottomStyle: "solid",
		borderBottomColor: tokens.colorNeutralStroke2,
		backgroundColor: tokens.colorNeutralBackground1,
	},
	toolbarTitle: {
		display: "flex",
		alignItems: "center",
		gap: tokens.spacingHorizontalS,
		minWidth: 0,
		overflow: "hidden",
	},
	toolbarActions: {
		display: "flex",
		gap: tokens.spacingHorizontalS,
		alignItems: "center",
		flexShrink: 0,
	},
	modeGroup: {
		display: "flex",
		backgroundColor: tokens.colorNeutralBackground3,
		borderRadius: tokens.borderRadiusMedium,
		padding: "2px",
		gap: "2px",
	},
	dividerVertical: {
		width: "1px",
		height: "24px",
		backgroundColor: tokens.colorNeutralStroke2,
		marginLeft: tokens.spacingHorizontalXS,
		marginRight: tokens.spacingHorizontalXS,
	},
	hiddenInput: {
		display: "none",
	},
	bindingLoadedBtn: {
		backgroundColor: tokens.colorPaletteGreenBackground1,
		color: tokens.colorPaletteGreenForeground1,
		borderTopRightRadius: 0,
		borderBottomRightRadius: 0,
		":hover": {
			backgroundColor: tokens.colorPaletteGreenBackground2,
		},
	},
	bindingLoadedIcon: {
		color: tokens.colorPaletteGreenForeground1,
	},
	bindingGroup: {
		display: "flex",
		alignItems: "center",
		backgroundColor: tokens.colorPaletteGreenBackground1,
		borderRadius: tokens.borderRadiusMedium,
	},
	bindingGroupDivider: {
		width: "1px",
		height: "16px",
		backgroundColor: tokens.colorPaletteGreenBorder1,
		opacity: 0.4,
	},
	bindingReuploadBtn: {
		color: tokens.colorPaletteGreenForeground1,
		borderTopLeftRadius: 0,
		borderBottomLeftRadius: 0,
		minWidth: "auto",
		":hover": {
			backgroundColor: tokens.colorPaletteGreenBackground2,
		},
	},
	content: {
		display: "flex",
		flex: 1,
		minHeight: 0,
		overflow: "hidden",
	},
	editorLayout: {
		display: "flex",
		flex: 1,
		minHeight: 0,
		height: "100%",
		overflow: "hidden",
	},
	treePanel: {
		flexShrink: 0,
		flexGrow: 1,
		flexBasis: "20%",
		minWidth: "120px",
		maxWidth: "420px",
		minHeight: 0,
		borderRightWidth: "1px",
		borderRightStyle: "solid",
		borderRightColor: tokens.colorNeutralStroke2,
		overflow: "hidden",
		display: "flex",
		flexDirection: "column",
		backgroundColor: tokens.colorNeutralBackground1,
	},
	previewPanel: {
		flex: 2,
		minWidth: 0,
		minHeight: 0,
		overflow: "hidden",
		display: "flex",
		flexDirection: "column",
		backgroundColor: tokens.colorNeutralBackground1,
	},
	previewPanelHeader: {
		display: "flex",
		alignItems: "center",
		justifyContent: "space-between",
		padding: `${tokens.spacingVerticalXS} ${tokens.spacingHorizontalM}`,
		borderBottomWidth: "1px",
		borderBottomStyle: "solid",
		borderBottomColor: tokens.colorNeutralStroke2,
		flexShrink: 0,
		height: "32px",
		boxSizing: "border-box" as const,
		backgroundColor: tokens.colorNeutralBackground1,
	},
	previewPanelHeaderLabel: {
		userSelect: "none",
		textTransform: "uppercase" as const,
		letterSpacing: "0.5px",
	},
	previewPanelBody: {
		flex: 1,
		minHeight: 0,
		overflowY: "auto",
		overflowX: "hidden",
		display: "flex",
		alignItems: "flex-start",
		justifyContent: "center",
		backgroundColor: tokens.colorNeutralBackground1,
	},
	previewCard: {
		width: "100%",
		maxWidth: "960px",
		padding: tokens.spacingHorizontalL,
	},
	propertyPanel: {
		flexShrink: 0,
		flexGrow: 0,
		flexBasis: "25%",
		minWidth: "140px",
		maxWidth: "380px",
		borderLeftWidth: "1px",
		borderLeftStyle: "solid",
		borderLeftColor: tokens.colorNeutralStroke2,
		overflow: "hidden",
		backgroundColor: tokens.colorNeutralBackground1,
		display: "flex",
		flexDirection: "column",
	},
	propertyPanelHeader: {
		display: "flex",
		alignItems: "center",
		justifyContent: "space-between",
		padding: `0 ${tokens.spacingHorizontalM}`,
		borderBottomWidth: "1px",
		borderBottomStyle: "solid",
		borderBottomColor: tokens.colorNeutralStroke2,
		flexShrink: 0,
		height: "32px",
		boxSizing: "border-box" as const,
		backgroundColor: tokens.colorNeutralBackground1,
	},
	propertyPanelBody: {
		height: "calc(100% - 32px)",
		overflowY: "auto",
		overflowX: "hidden",
	},
	propertyPanelHeaderLabel: {
		userSelect: "none",
		textTransform: "uppercase" as const,
		letterSpacing: "0.5px",
	},
	propertyPanelHeaderBadge: {
		fontSize: "11px",
		backgroundColor: tokens.colorBrandBackground2,
		color: tokens.colorBrandForeground2,
		borderRadius: tokens.borderRadiusMedium,
		paddingLeft: tokens.spacingHorizontalS,
		paddingRight: tokens.spacingHorizontalS,
		paddingTop: "2px",
		paddingBottom: "2px",
	},
	propertyPanelHeaderLeft: {
		display: "flex",
		alignItems: "center",
		gap: tokens.spacingHorizontalS,
	},
	propertyPanelCollapsed: {
		flexShrink: 0,
		display: "flex",
		flexDirection: "column",
		alignItems: "center",
		gap: tokens.spacingVerticalS,
		paddingTop: tokens.spacingVerticalM,
		paddingBottom: tokens.spacingVerticalM,
		width: "36px",
		minWidth: "36px",
		borderLeftWidth: "1px",
		borderLeftStyle: "solid",
		borderLeftColor: tokens.colorNeutralStroke2,
		backgroundColor: tokens.colorNeutralBackground1,
		cursor: "pointer",
		":hover": {
			backgroundColor: tokens.colorNeutralBackground1Hover,
		},
	},
	collapsedLabel: {
		writingMode: "vertical-rl",
		userSelect: "none",
	},
	jsonView: {
		flex: 1,
		overflow: "auto",
		padding: tokens.spacingHorizontalXL,
		backgroundColor: tokens.colorNeutralBackground3,
		display: "flex",
		justifyContent: "center",
	},
	jsonContainer: {
		display: "flex",
		flexDirection: "column",
		gap: tokens.spacingVerticalM,
		maxWidth: "800px",
		width: "100%",
	},
	jsonToolbar: {
		display: "flex",
		alignItems: "center",
		gap: tokens.spacingHorizontalS,
		"& button": {
			display: "inline-flex",
			alignItems: "center",
		},
	},
	jsonError: {
		display: "flex",
		flexDirection: "column",
		gap: tokens.spacingVerticalXS,
		backgroundColor: tokens.colorPaletteRedBackground1,
		borderLeftWidth: "3px",
		borderLeftStyle: "solid",
		borderLeftColor: tokens.colorPaletteRedBorder1,
		borderRadius: tokens.borderRadiusMedium,
		paddingTop: tokens.spacingVerticalS,
		paddingBottom: tokens.spacingVerticalS,
		paddingLeft: tokens.spacingHorizontalM,
		paddingRight: tokens.spacingHorizontalM,
		color: tokens.colorPaletteRedForeground1,
	},
	jsonPre: {
		fontFamily: '"Cascadia Code", "Fira Code", "Consolas", monospace',
		fontSize: "13px",
		lineHeight: "20px",
		backgroundColor: tokens.colorNeutralBackground1,
		borderRadius: tokens.borderRadiusLarge,
		boxShadow: tokens.shadow4,
		padding: tokens.spacingHorizontalL,
		maxWidth: "800px",
		width: "100%",
		whiteSpace: "pre-wrap",
		wordBreak: "break-word",
		color: tokens.colorNeutralForeground1,
		margin: "0",
	},
	fullPreview: {
		flex: 1,
		overflow: "auto",
		padding: tokens.spacingHorizontalXL,
		backgroundColor: tokens.colorNeutralBackground3,
		display: "flex",
		justifyContent: "center",
		alignItems: "flex-start",
	},
	fullPreviewCard: {
		width: "100%",
		maxWidth: "800px",
		backgroundColor: tokens.colorNeutralBackground1,
		borderRadius: tokens.borderRadiusLarge,
		boxShadow: tokens.shadow8,
		padding: tokens.spacingHorizontalXL,
	},
	emptyState: {
		flex: 1,
		display: "flex",
		flexDirection: "column",
		alignItems: "center",
		justifyContent: "center",
		gap: tokens.spacingVerticalM,
		color: tokens.colorNeutralForeground3,
		padding: tokens.spacingHorizontalXL,
	},
	bindingDialogSurface: {
		maxWidth: "640px",
		width: "90vw",
	},
	bindingPreviewPre: {
		fontFamily: '"Cascadia Code", "Fira Code", "Consolas", monospace',
		fontSize: "13px",
		lineHeight: "20px",
		backgroundColor: tokens.colorNeutralBackground3,
		borderRadius: tokens.borderRadiusMedium,
		padding: tokens.spacingHorizontalM,
		maxHeight: "60vh",
		overflowY: "auto",
		whiteSpace: "pre-wrap",
		wordBreak: "break-word",
		color: tokens.colorNeutralForeground1,
		margin: "0",
	},
});
