import { tokens, shorthands } from "@fluentui/react-components";
import type { GriffelStyle } from "@fluentui/react-components";

export const tableStyles: Record<string, GriffelStyle> = {
	root: {
		display: "flex",
		flexDirection: "column",
		gap: tokens.spacingVerticalXS,
		width: "100%",
	},
	summaryTilesRow: {
		display: "flex",
		alignItems: "stretch",
		flexWrap: "wrap",
		gap: tokens.spacingHorizontalM,
	},
	summaryTiles: {
		flex: 1,
		display: "grid",
		gridTemplateColumns: "repeat(auto-fit, minmax(120px, 1fr))",
		gap: "10px",
	},
	summaryTile: {
		position: "relative",
		overflow: "hidden",
		display: "flex",
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "flex-start",
		columnGap: "12px",
		minHeight: "68px",
		width: "100%",
		...shorthands.padding("12px", "16px"),
		...shorthands.border("1px", "solid", tokens.colorNeutralStroke2),
		boxSizing: "border-box",
		borderRadius: tokens.borderRadiusLarge,
		backgroundColor: tokens.colorNeutralBackground1,
		boxShadow: tokens.shadow2,
		cursor: "pointer",
		":focus-visible": {
			outlineStyle: "solid",
			outlineWidth: "2px",
			outlineColor: tokens.colorStrokeFocus2,
			outlineOffset: "-1px",
		},
	},
	summaryTileActive: {
		boxShadow: tokens.shadow2,
	},
	summaryTileIcon: {
		display: "flex",
		alignItems: "center",
		justifyContent: "center",
		flexShrink: 0,
		width: "32px",
		height: "32px",
		...shorthands.borderRadius(tokens.borderRadiusCircular),
		backgroundColor: tokens.colorBrandBackground2,
		color: tokens.colorBrandForeground1,
	},
	summaryTileText: {
		display: "flex",
		flexDirection: "column",
		alignItems: "flex-start",
		minWidth: 0,
	},
	summaryTileCount: {
		fontSize: "1.15rem",
		fontWeight: 700,
		lineHeight: "1.2",
		color: tokens.colorNeutralForeground1,
	},
	summaryTileLabel: {
		fontSize: "0.7rem",
		color: tokens.colorNeutralForeground2,
		fontWeight: tokens.fontWeightRegular,
		textAlign: "left" as const,
		textOverflow: "ellipsis",
		whiteSpace: "nowrap" as const,
		overflow: "hidden",
		maxWidth: "100%",
		marginTop: "2px",
	},
	toolbar: {
		display: "flex",
		alignItems: "center",
		justifyContent: "space-between",
		gap: "12px",
		paddingBottom: "4px",
		paddingTop: "4px",
	},
	label: {
		fontSize: tokens.fontSizeBase200,
		fontWeight: tokens.fontWeightSemibold,
		color: tokens.colorNeutralForeground2,
		paddingLeft: "2px",
		whiteSpace: "nowrap" as const,
	},
	recordCount: {
		fontSize: tokens.fontSizeBase200,
		color: tokens.colorNeutralForeground2,
		fontStyle: "italic",
		paddingLeft: "2px",
		whiteSpace: "nowrap" as const,
	},
	searchBox: {
		maxWidth: "250px",
		width: "250px",
		marginLeft: "auto",
		...shorthands.border("1px", "solid", tokens.colorNeutralStroke1),
		borderBottomColor: tokens.colorNeutralStroke1,
		"&::before": {
			display: "none",
		},
		"&::after": {
			display: "none",
		},
		"& .fui-Input__input::placeholder": {
			color: tokens.colorNeutralForeground3,
			opacity: 1,
		},
		"& input::placeholder": {
			color: tokens.colorNeutralForeground3,
			opacity: 1,
		},
	},
	tableWrapper: {
		overflowX: "auto",
		scrollbarWidth: "thin" as const,
		...shorthands.border("1px", "solid", tokens.colorNeutralStroke2),
		borderRadius: tokens.borderRadiusMedium,
		"& tbody tr:last-child": {
			borderBottom: "none",
		},
	},
	headerRow: {
		backgroundColor: tokens.colorNeutralBackground2,
		fontWeight: tokens.fontWeightBold,
	},
	headerCell: {
		fontWeight: tokens.fontWeightSemibold,
		color: tokens.colorNeutralForeground1,
		"& button": {
			fontWeight: tokens.fontWeightSemibold,
		},
	},
	cellButton: {
		minWidth: "auto",
		fontSize: tokens.fontSizeBase200,
		...shorthands.padding("2px", "10px"),
	},
	clickableRow: {
		cursor: "pointer",
	},
	sortableHeader: {
		cursor: "pointer",
		userSelect: "none" as const,
	},
	sortIcon: {
		display: "inline-flex",
		verticalAlign: "middle",
		marginLeft: "4px",
		flexShrink: 0,
	},
	emptyMessageRow: {
		display: "flex",
		justifyContent: "center",
		alignItems: "center",
		padding: "32px 16px",
		color: tokens.colorNeutralForeground3,
		fontSize: tokens.fontSizeBase300,
		fontStyle: "italic",
	},
};
