import { makeStyles, shorthands, tokens } from "@fluentui/react-components";

export const useTemplateDesignStyles = makeStyles({
	panelBusyOverlay: {
		position: "absolute",
		inset: 0,
		zIndex: 50,
		backgroundColor: "rgba(255,255,255,0.5)",
		cursor: "wait",
	},
	shimmerRoot: {
		display: "flex",
		flexDirection: "column",
		flex: 1,
		minHeight: 0,
		...shorthands.borderRadius(tokens.borderRadiusLarge),
		boxShadow: tokens.shadow4,
		overflow: "hidden",
		backgroundColor: tokens.colorNeutralBackground1,
	},
	shimmerToolbar: {
		display: "flex",
		alignItems: "center",
		justifyContent: "space-between",
		...shorthands.padding(tokens.spacingVerticalS, tokens.spacingHorizontalL),
		...shorthands.borderBottom("1px", "solid", tokens.colorNeutralStroke2),
	},
	shimmerToolbarLeft: {
		display: "flex",
		alignItems: "center",
		...shorthands.gap("8px"),
	},
	shimmerToolbarRight: {
		display: "flex",
		alignItems: "center",
		...shorthands.gap("8px"),
	},
	shimmerContent: {
		display: "flex",
		flex: 1,
		minHeight: 0,
		overflow: "hidden",
	},
	shimmerTreePanel: {
		display: "flex",
		flexDirection: "column",
		flexBasis: "20%",
		minWidth: "120px",
		...shorthands.gap("10px"),
		...shorthands.padding("14px", "12px"),
		...shorthands.borderRight("1px", "solid", tokens.colorNeutralStroke2),
	},
	shimmerPreviewPanel: {
		display: "flex",
		flexDirection: "column",
		flex: 2,
		...shorthands.gap("12px"),
		...shorthands.padding("10px", "16px"),
		alignItems: "center",
	},
	shimmerPreviewCard: {
		display: "flex",
		flexDirection: "column",
		width: "100%",
		maxWidth: "460px",
		...shorthands.gap("10px"),
		...shorthands.padding("16px"),
		...shorthands.border("1px", "solid", tokens.colorNeutralStroke2),
		...shorthands.borderRadius(tokens.borderRadiusMedium),
	},
	shimmerPropertyPanel: {
		display: "flex",
		flexDirection: "column",
		flexBasis: "25%",
		minWidth: "140px",
		...shorthands.gap("12px"),
		...shorthands.padding("14px", "12px"),
		...shorthands.borderLeft("1px", "solid", tokens.colorNeutralStroke2),
	},
});
