import { makeStyles, shorthands, tokens } from "@fluentui/react-components";

export const useChatNavBarStyles = makeStyles({
	root: {
		display: "flex",
		flexDirection: "column",
		width: "260px",
		height: "100%",
		backgroundColor: "var(--agent-chat-sidebar-bg)",
		...shorthands.borderRight("1px", "solid", "var(--agent-chat-border)"),
		flexShrink: 0,
		overflowY: "auto",
		overflowX: "hidden",
		transition: "width 0.2s ease",
	},
	rootCollapsed: {
		width: "44px",
	},
	topActions: {
		display: "flex",
		alignItems: "center",
		justifyContent: "space-between",
		height: "42px",
		...shorthands.padding("0", "10px"),
		...shorthands.borderBottom("1px", "solid", "var(--agent-chat-border)"),
		flexShrink: 0,
		boxSizing: "border-box",
		color: "var(--agent-chat-brand)",
	},
	topActionsCollapsed: {
		justifyContent: "center",
		...shorthands.padding("0", "4px"),
	},
	navButton: {
		display: "flex",
		alignItems: "center",
		...shorthands.gap("10px"),
		width: "100%",
		...shorthands.padding("10px", "14px"),
		...shorthands.border("none"),
		...shorthands.borderRadius("10px"),
		backgroundColor: "transparent",
		color: "var(--agent-chat-fg)",
		fontSize: tokens.fontSizeBase300,
		fontWeight: tokens.fontWeightRegular,
		cursor: "pointer",
		textAlign: "left",
		":hover": {
			backgroundColor: "var(--agent-chat-hover)",
		},
	},
	navButtonActive: {
		backgroundColor: "var(--agent-chat-surface)",
		boxShadow: "inset 0 0 0 1px var(--agent-chat-border)",
		fontWeight: tokens.fontWeightSemibold,
	},
	navButtonCollapsed: {
		justifyContent: "center",
		width: "30px",
		height: "30px",
		...shorthands.padding("0"),
		margin: "0 auto",
	},
	navSection: {
		display: "flex",
		flexDirection: "column",
		...shorthands.padding("6px", "6px"),
		...shorthands.gap("6px"),
	},
	iconButton: {
		minWidth: "32px",
		width: "32px",
		height: "32px",
		...shorthands.borderRadius("6px"),
		...shorthands.padding("0"),
		...shorthands.border("none"),
		backgroundColor: "transparent",
		color: "var(--agent-chat-muted)",
		cursor: "pointer",
		display: "inline-flex",
		alignItems: "center",
		justifyContent: "center",
		":hover": {
			backgroundColor: "var(--agent-chat-hover)",
			color: "var(--agent-chat-fg)",
		},
	},
});
