import { makeStyles, tokens } from "@fluentui/react-components";

export const usePropertyPanelStyles = makeStyles({
	root: {
		display: "flex",
		flexDirection: "column",
		paddingLeft: tokens.spacingHorizontalM,
		paddingRight: tokens.spacingHorizontalM,
		paddingTop: tokens.spacingVerticalS,
		paddingBottom: tokens.spacingVerticalL,
		gap: tokens.spacingVerticalM,
	},
	header: {
		display: "flex",
		alignItems: "center",
		gap: tokens.spacingHorizontalS,
		paddingTop: tokens.spacingVerticalXS,
		paddingBottom: tokens.spacingVerticalS,
	},
	headerLabel: {
		textTransform: "uppercase" as const,
		letterSpacing: "0.5px",
	},
	headerBadge: {
		fontSize: "11px",
		backgroundColor: tokens.colorBrandBackground2,
		color: tokens.colorBrandForeground2,
		borderRadius: tokens.borderRadiusMedium,
		paddingLeft: tokens.spacingHorizontalS,
		paddingRight: tokens.spacingHorizontalS,
		paddingTop: "2px",
		paddingBottom: "2px",
	},
	sectionGroup: {
		display: "flex",
		flexDirection: "column",
		backgroundColor: tokens.colorNeutralBackground2,
		borderRadius: tokens.borderRadiusMedium,
		overflow: "hidden",
	},
	sectionHeader: {
		display: "flex",
		alignItems: "center",
		justifyContent: "space-between",
		paddingTop: tokens.spacingVerticalS,
		paddingBottom: tokens.spacingVerticalS,
		paddingLeft: tokens.spacingHorizontalM,
		paddingRight: tokens.spacingHorizontalM,
		cursor: "pointer",
		userSelect: "none",
		":hover": {
			backgroundColor: tokens.colorNeutralBackground2Hover,
		},
	},
	sectionTitle: {
		textTransform: "uppercase" as const,
		letterSpacing: "0.5px",
		color: tokens.colorNeutralForeground3,
	},
	sectionChevron: {
		color: tokens.colorNeutralForeground3,
		transition: "transform 0.15s ease",
		fontSize: "16px",
		flexShrink: 0,
	},
	sectionChevronCollapsed: {
		transform: "rotate(-90deg)",
	},
	sectionBody: {
		display: "flex",
		flexDirection: "column",
		gap: tokens.spacingVerticalS,
		padding: `${tokens.spacingVerticalM} ${tokens.spacingHorizontalM} ${tokens.spacingHorizontalM}`,
	},
	sectionBodyHidden: {
		display: "none",
	},
	field: {
		display: "flex",
		flexDirection: "column",
		gap: tokens.spacingVerticalXS,
	},
	row: {
		display: "flex",
		gap: tokens.spacingHorizontalM,
		alignItems: "center",
		flexWrap: "wrap" as const,
	},
	halfField: {
		display: "flex",
		flexDirection: "column",
		gap: tokens.spacingVerticalXS,
		flex: 1,
		minWidth: 0,
		overflow: "hidden",
	},
	empty: {
		display: "flex",
		flexDirection: "column",
		alignItems: "center",
		justifyContent: "center",
		height: "100%",
		gap: tokens.spacingVerticalM,
		color: tokens.colorNeutralForeground3,
		padding: tokens.spacingHorizontalL,
		textAlign: "center" as const,
	},
	emptyIcon: {
		fontSize: "32px",
		color: tokens.colorNeutralForeground4,
	},
	columnCard: {
		display: "flex",
		flexDirection: "column",
		gap: tokens.spacingVerticalXS,
		backgroundColor: tokens.colorNeutralBackground1,
		borderRadius: tokens.borderRadiusMedium,
		padding: tokens.spacingHorizontalS,
		border: `1px solid ${tokens.colorNeutralStroke2}`,
	},
	columnHeader: {
		display: "flex",
		justifyContent: "space-between",
		alignItems: "center",
	},
	addColumnBtn: {
		alignSelf: "flex-start",
	},
});
