import { makeStyles, shorthands, tokens } from "@fluentui/react-components";

const shimmer = {
	"0%": { backgroundPosition: "200% 0" },
	"100%": { backgroundPosition: "-200% 0" },
};

const fadeIn = {
	from: { opacity: 0, transform: "translateY(4px)" },
	to: { opacity: 1, transform: "translateY(0)" },
};

export const useStarterPromptChipsStyles = makeStyles({
	root: {
		width: "100%",
		maxWidth: "860px",
		display: "flex",
		flexWrap: "wrap",
		justifyContent: "center",
		...shorthands.gap("8px"),
		...shorthands.padding("2px", "8px", "0"),
		boxSizing: "border-box",
		animationName: fadeIn,
		animationDuration: "0.25s",
		animationTimingFunction: "ease-out",
		animationFillMode: "both",
	},
	chip: {
		...shorthands.padding("9px", "14px"),
		...shorthands.border("1px", "solid", "var(--agent-chat-border)"),
		...shorthands.borderRadius("8px"),
		backgroundColor: "var(--agent-chat-card)",
		color: "var(--agent-chat-fg)",
		fontSize: tokens.fontSizeBase200,
		fontWeight: tokens.fontWeightMedium,
		cursor: "pointer",
		fontFamily: "inherit",
		":hover": { backgroundColor: "var(--agent-chat-hover)" },
	},
	moreWrapper: { position: "relative" },
	moreChip: {
		...shorthands.padding("9px", "14px"),
		...shorthands.border("1px", "solid", "var(--agent-chat-brand)"),
		...shorthands.borderRadius("8px"),
		backgroundColor: "var(--agent-chat-card)",
		color: "var(--agent-chat-brand)",
		fontSize: tokens.fontSizeBase200,
		fontWeight: tokens.fontWeightSemibold,
		cursor: "pointer",
		fontFamily: "inherit",
		":hover": { backgroundColor: "var(--agent-chat-hover)" },
	},
	overflowDropdown: {
		position: "absolute",
		top: "100%",
		left: "0",
		marginTop: "4px",
		backgroundColor: "var(--agent-chat-card)",
		...shorthands.border("1px", "solid", "var(--agent-chat-border)"),
		...shorthands.borderRadius("8px"),
		boxShadow: tokens.shadow8,
		zIndex: 10,
		minWidth: "160px",
		maxHeight: "220px",
		overflowY: "auto",
		...shorthands.padding("4px", "0"),
	},
	overflowItem: {
		display: "block",
		width: "100%",
		textAlign: "left",
		backgroundColor: "transparent",
		...shorthands.border("none"),
		...shorthands.padding("8px", "14px"),
		color: "var(--agent-chat-fg)",
		fontSize: tokens.fontSizeBase200,
		cursor: "pointer",
		whiteSpace: "nowrap",
		fontFamily: "inherit",
		":hover": { backgroundColor: "var(--agent-chat-hover)" },
	},
	skeletonContainer: {
		display: "flex",
		flexDirection: "column",
		alignItems: "center",
		rowGap: "8px",
		width: "100%",
		maxWidth: "860px",
		...shorthands.padding("2px", "8px", "0"),
		boxSizing: "border-box",
	},
	skeletonRow: {
		display: "flex",
		justifyContent: "center",
		columnGap: "8px",
		width: "100%",
		flexWrap: "nowrap",
	},
	shimmerChip: {
		height: "36px",
		...shorthands.borderRadius("8px"),
		backgroundColor: "rgba(0, 0, 0, 0.04)",
		backgroundImage:
			"linear-gradient(90deg, rgba(0,0,0,0.04) 0%, rgba(0,0,0,0.02) 40%, rgba(0,0,0,0.04) 80%)",
		backgroundSize: "200% 100%",
		animationName: shimmer,
		animationDuration: "2s",
		animationTimingFunction: "ease-in-out",
		animationIterationCount: "infinite",
	},
});
