import { tokens } from "@fluentui/react-components";
import type { GriffelStyle } from "@fluentui/react-components";

export const homeStyles: Record<string, GriffelStyle> = {
	root: {
		display: "flex",
		flexDirection: "column",
		height: "100vh",
		width: "100%",
		overflow: "hidden",
		backgroundColor: tokens.colorNeutralBackground2,
	},
	navBar: {
		display: "flex",
		alignItems: "center",
		justifyContent: "space-between",
		height: "36px",
		paddingLeft: "20px",
		paddingRight: "20px",
		boxSizing: "border-box",
		flexShrink: 0,
		backgroundColor: tokens.colorBrandBackground,
		borderBottom: `1px solid ${tokens.colorNeutralStroke2}`,
		position: "relative" as const,
		zIndex: 1,
	},
	navBarTitle: {
		margin: 0,
		color: tokens.colorNeutralForegroundOnBrand,
		fontSize: tokens.fontSizeBase300,
		fontWeight: tokens.fontWeightSemibold,
	},
	assistantToggleButton: {
		minWidth: "28px",
		width: "28px",
		height: "28px",
		border: "none",
		borderRadius: 0,
		padding: 0,
		display: "inline-flex",
		alignItems: "center",
		justifyContent: "center",
		cursor: "pointer",
		backgroundColor: "transparent",
		color: "rgba(255,255,255,0.7)",
		":hover": {
			backgroundColor: "transparent",
			color: "#ffffff",
		},
	},
	assistantToggleButtonActive: {
		color: "#ffffff",
		backgroundColor: "transparent",
		":hover": {
			backgroundColor: "transparent",
			color: "#ffffff",
		},
	},
	content: {
		position: "relative",
		display: "flex",
		flexDirection: "row",
		flex: 1,
		minHeight: 0,
		overflow: "hidden",
	},
	mainArea: {
		flex: 1,
		display: "flex",
		alignItems: "center",
		justifyContent: "center",
		minWidth: 0,
		overflow: "auto",
	},
	assistantContainer: {
		flexShrink: 0,
		display: "flex",
		minHeight: 0,
		overflow: "hidden",
		transitionProperty: "opacity",
		transitionDuration: "0.25s",
		transitionTimingFunction: "ease",
		"@media (max-width: 768px)": {
			position: "absolute" as const,
			top: 0,
			left: 0,
			right: 0,
			bottom: 0,
			zIndex: 10,
			width: "100%",
			height: "100%",
			overflow: "visible",
		},
	},
	assistantContainerHidden: {
		width: "0px",
		opacity: 0,
		overflow: "hidden",
	},
};
