import { makeStyles, shorthands, tokens } from "@fluentui/react-components";

export const useChatInputStyles = makeStyles({
	composerContainer: {
		position: "relative",
		width: "100%",
		maxWidth: "920px",
		alignSelf: "center",
		...shorthands.padding("4px", "12px", "18px"),
		boxSizing: "border-box",
		flexShrink: 0,
	},
	composer: {
		display: "flex",
		flexDirection: "column",
		...shorthands.border("1px", "solid", "var(--agent-chat-border)"),
		...shorthands.borderRadius("16px"),
		backgroundColor: "var(--agent-chat-card)",
		...shorthands.padding("12px", "12px", "8px"),
		boxShadow: tokens.shadow8,
		transitionProperty: "box-shadow",
		transitionDuration: "0.2s",
		":focus-within": {
			...shorthands.border("1px", "solid", "var(--agent-chat-brand)"),
			boxShadow: tokens.shadow16,
		},
	},
	composerInput: {
		width: "100%",
		border: "none",
		outlineStyle: "none",
		resize: "none" as const,
		backgroundColor: "transparent",
		color: "var(--agent-chat-fg)",
		fontFamily: tokens.fontFamilyBase,
		fontSize: tokens.fontSizeBase300,
		lineHeight: tokens.lineHeightBase300,
		minHeight: "28px",
		maxHeight: "120px",
		paddingRight: "4px",
		"::placeholder": {
			color: "var(--agent-chat-muted)",
		},
	},
	composerFooter: {
		display: "flex",
		alignItems: "center",
		justifyContent: "space-between",
		...shorthands.gap("8px"),
	},
	leftTools: {
		display: "flex",
		alignItems: "center",
		...shorthands.gap("4px"),
		minWidth: 0,
	},
	iconButton: {
		minWidth: "34px",
		width: "34px",
		height: "34px",
		...shorthands.borderRadius("50%"),
		...shorthands.padding("0"),
		...shorthands.border("none"),
		backgroundColor: "transparent",
		color: "var(--agent-chat-muted)",
		cursor: "pointer",
		display: "inline-flex",
		alignItems: "center",
		justifyContent: "center",
		":hover": {
			backgroundColor: "var(--agent-chat-hover)",
			color: "var(--agent-chat-fg)",
		},
	},
	rightTools: {
		display: "flex",
		alignItems: "center",
		...shorthands.gap("6px"),
	},
	sendButton: {
		minWidth: "36px",
		width: "36px",
		height: "36px",
		...shorthands.borderRadius("50%"),
		...shorthands.padding("0"),
		...shorthands.border("none"),
		backgroundColor: "transparent",
		color: "var(--agent-chat-muted)",
		cursor: "pointer",
		display: "inline-flex",
		alignItems: "center",
		justifyContent: "center",
	},
	sendButtonActive: {
		color: "#ffffff",
		backgroundColor: "var(--agent-chat-brand)",
		":hover": {
			backgroundColor: "#0c5da5",
			color: "#ffffff",
		},
	},

	/* ── Autocomplete suggestions ── */
	suggestionsDropdown: {
		position: "absolute",
		bottom: "100%",
		left: "12px",
		right: "12px",
		backgroundColor: "var(--agent-chat-card)",
		...shorthands.borderRadius("10px"),
		...shorthands.border("1px", "solid", "var(--agent-chat-border)"),
		boxShadow: tokens.shadow16,
		maxHeight: "220px",
		overflowY: "auto",
		marginBottom: "4px",
		zIndex: 10,
		...shorthands.padding("4px", "0"),
	},
	suggestionItem: {
		display: "flex",
		flexDirection: "column",
		alignItems: "flex-start",
		width: "100%",
		...shorthands.padding("6px", "14px"),
		...shorthands.border("none"),
		...shorthands.borderBottom("1px", "solid", "var(--agent-chat-border)"),
		backgroundColor: "transparent",
		cursor: "pointer",
		textAlign: "left",
		fontFamily: "inherit",
		transitionProperty: "background-color",
		transitionDuration: "0.15s",
		":hover": {
			backgroundColor: "var(--agent-chat-hover)",
		},
		":last-child": {
			borderBottomStyle: "none",
		},
	},
	suggestionItemActive: {
		backgroundColor: "var(--agent-chat-hover)",
	},
	suggestionTitle: {
		fontSize: tokens.fontSizeBase300,
		fontWeight: tokens.fontWeightSemibold,
		color: "var(--agent-chat-fg)",
		lineHeight: tokens.lineHeightBase300,
	},
	suggestionPrompt: {
		fontSize: tokens.fontSizeBase200,
		color: "var(--agent-chat-muted)",
		marginTop: "1px",
		whiteSpace: "nowrap",
		overflow: "hidden",
		textOverflow: "ellipsis",
		maxWidth: "100%",
		lineHeight: tokens.lineHeightBase100,
	},

	/* ── Prompts popover ── */
	promptsPopover: {
		display: "flex",
		flexDirection: "column",
		width: "320px",
		maxHeight: "320px",
		...shorthands.padding("0"),
	},
	promptsSearchWrap: {
		position: "relative",
		...shorthands.padding("8px", "8px", "4px"),
	},
	promptsSearchIcon: {
		position: "absolute",
		left: "16px",
		top: "50%",
		transform: "translateY(-50%)",
		color: "var(--agent-chat-muted)",
		pointerEvents: "none",
	},
	promptsSearchInput: {
		width: "100%",
		boxSizing: "border-box",
		...shorthands.padding("6px", "10px", "6px", "28px"),
		...shorthands.border("1px", "solid", "var(--agent-chat-border)"),
		...shorthands.borderRadius("8px"),
		fontSize: tokens.fontSizeBase200,
		color: "var(--agent-chat-fg)",
		backgroundColor: "var(--agent-chat-card)",
		outlineStyle: "none",
		fontFamily: "inherit",
		"::placeholder": { color: "var(--agent-chat-muted)" },
	},
	promptsList: {
		display: "flex",
		flexDirection: "column",
		flex: 1,
		minHeight: 0,
		overflowY: "auto",
		...shorthands.padding("4px", "0", "6px"),
	},
	promptsItem: {
		position: "relative",
		display: "flex",
		flexDirection: "column",
		alignItems: "flex-start",
		width: "100%",
		...shorthands.padding("8px", "14px"),
		...shorthands.border("none"),
		backgroundColor: "transparent",
		color: "inherit",
		cursor: "pointer",
		textAlign: "left",
		fontFamily: "inherit",
		transitionProperty: "background-color",
		transitionDuration: "0.15s",
		"::after": {
			content: '""',
			position: "absolute",
			left: "14px",
			right: "14px",
			bottom: "0",
			height: "1px",
			backgroundColor: tokens.colorNeutralStroke3,
			opacity: 0.6,
		},
		":last-child::after": {
			display: "none",
		},
		":hover": {
			backgroundColor: "var(--agent-chat-hover)",
		},
		":focus-visible": {
			backgroundColor: "var(--agent-chat-hover)",
			outlineStyle: "none",
		},
	},
	promptsItemTitle: {
		fontSize: tokens.fontSizeBase200,
		fontWeight: tokens.fontWeightRegular,
		color: "inherit",
		lineHeight: tokens.lineHeightBase200,
	},
	promptsEmpty: {
		...shorthands.padding("12px", "14px"),
		fontSize: tokens.fontSizeBase200,
		color: "var(--agent-chat-muted)",
	},
});
