import { makeStyles, shorthands, tokens } from "@fluentui/react-components";

export const usePromptFormStyles = makeStyles({
	wrapper: {
		display: "flex",
		flexDirection: "column",
		width: "100%",
		maxWidth: "920px",
		alignSelf: "center",
		marginLeft: "auto",
		marginRight: "auto",
		...shorthands.padding("0", "12px"),
		boxSizing: "border-box",
	},
	card: {
		display: "flex",
		flexDirection: "column",
		maxWidth: "480px",
		backgroundColor: "var(--agent-chat-surface)",
		...shorthands.borderRadius("12px"),
		...shorthands.border("1px", "solid", "var(--agent-chat-border)"),
		borderLeftWidth: "3px",
		borderLeftStyle: "solid",
		borderLeftColor: tokens.colorCompoundBrandStroke,
		boxSizing: "border-box",
		overflow: "hidden",
		transitionProperty: "border-color",
		transitionDuration: "0.15s",
		transitionTimingFunction: "ease",
		":focus-within": {
			borderTopColor: tokens.colorCompoundBrandStroke,
			borderRightColor: tokens.colorCompoundBrandStroke,
			borderBottomColor: tokens.colorCompoundBrandStroke,
		},
	},
	topRow: {
		display: "flex",
		alignItems: "center",
		justifyContent: "space-between",
		...shorthands.padding("10px", "14px", "0", "14px"),
	},
	titleBadge: {
		display: "inline-flex",
		alignItems: "center",
		columnGap: "4px",
		fontSize: tokens.fontSizeBase200,
		fontWeight: tokens.fontWeightSemibold,
		color: "var(--agent-chat-brand)",
		lineHeight: "20px",
		userSelect: "none",
	},
	dismissButton: {
		minWidth: "24px",
		width: "24px",
		height: "24px",
		...shorthands.borderRadius("6px"),
		...shorthands.padding("0"),
		color: "var(--agent-chat-muted)",
		":hover": {
			color: "var(--agent-chat-fg)",
			backgroundColor: "var(--agent-chat-hover)",
		},
	},
	fields: {
		display: "flex",
		flexDirection: "column",
		rowGap: "10px",
		...shorthands.padding("10px", "14px"),
		maxHeight: "240px",
		overflowY: "auto",
	},
	fieldGroup: {
		display: "flex",
		flexDirection: "column",
		rowGap: "4px",
	},
	fieldLabel: {
		fontSize: tokens.fontSizeBase200,
		fontWeight: tokens.fontWeightSemibold,
		color: "var(--agent-chat-fg)",
		lineHeight: "16px",
		paddingLeft: "2px",
		display: "inline-flex",
		alignItems: "center",
		columnGap: "3px",
	},
	requiredMark: {
		color: tokens.colorPaletteRedForeground1,
		fontSize: tokens.fontSizeBase200,
		lineHeight: "16px",
	},
	optionalHint: {
		color: "var(--agent-chat-muted)",
		fontSize: tokens.fontSizeBase100,
		fontWeight: tokens.fontWeightRegular,
		lineHeight: "16px",
	},
	input: {
		width: "100%",
		boxSizing: "border-box",
		backgroundColor: "var(--agent-chat-surface)",
		color: "var(--agent-chat-fg)",
		...shorthands.borderRadius("8px"),
		...shorthands.border("1px", "solid", "var(--agent-chat-border)"),
		...shorthands.padding("7px", "10px"),
		fontSize: tokens.fontSizeBase200,
		fontFamily: "inherit",
		outlineStyle: "none",
		":focus": {
			...shorthands.border("1px", "solid", tokens.colorCompoundBrandStroke),
		},
		"::placeholder": {
			color: "var(--agent-chat-muted)",
		},
	},
	actionBar: {
		display: "flex",
		alignItems: "center",
		justifyContent: "flex-end",
		...shorthands.padding("0", "14px", "10px", "14px"),
	},
	sendButton: {
		minWidth: "32px",
		width: "32px",
		height: "32px",
		...shorthands.borderRadius("50%"),
		...shorthands.padding("0"),
		flexShrink: 0,
		color: "var(--agent-chat-muted)",
		backgroundColor: "transparent",
		transitionProperty: "background-color, color",
		transitionDuration: "0.15s",
		":hover": {
			backgroundColor: "transparent",
			color: "var(--agent-chat-muted)",
		},
	},
	sendButtonActive: {
		color: "var(--agent-chat-user-fg)",
		backgroundColor: "var(--agent-chat-brand)",
		":hover": {
			backgroundColor: "var(--agent-chat-brand-hover)",
			color: "var(--agent-chat-user-fg)",
		},
	},
});
