import { makeStyles, shorthands, tokens } from "@fluentui/react-components";

export const useStarterPromptFormStyles = makeStyles({
	formField: {
		display: "flex",
		flexDirection: "column",
		...shorthands.gap("6px"),
	},
	formFieldHeader: {
		display: "flex",
		alignItems: "flex-start",
		...shorthands.gap("8px"),
	},
	fieldIcon: {
		display: "inline-flex",
		alignItems: "center",
		justifyContent: "center",
		width: "20px",
		height: "20px",
		color: tokens.colorBrandForeground1,
		flexShrink: 0,
	},
	fieldTitleGroup: { minWidth: 0, flex: 1 },
	fieldTitle: {
		fontSize: tokens.fontSizeBase200,
		fontWeight: tokens.fontWeightSemibold,
		color: tokens.colorNeutralForeground1,
		lineHeight: tokens.lineHeightBase200,
	},
	fieldDescription: {
		marginTop: "2px",
		fontSize: tokens.fontSizeBase100,
		color: tokens.colorNeutralForeground2,
		lineHeight: tokens.lineHeightBase200,
	},
	fieldContent: {
		paddingLeft: "28px",
		boxSizing: "border-box",
	},
	input: {
		width: "100%",
		maxWidth: "100%",
		minWidth: 0,
		boxSizing: "border-box",
		...shorthands.padding("6px", "10px"),
		...shorthands.border("1px", "solid", tokens.colorNeutralStroke1),
		...shorthands.borderRadius(tokens.borderRadiusMedium),
		fontSize: tokens.fontSizeBase200,
		color: tokens.colorNeutralForeground1,
		backgroundColor: tokens.colorNeutralBackground1,
		outlineStyle: "none",
		fontFamily: "inherit",
		"::placeholder": { color: tokens.colorNeutralForeground4 },
	},
	textarea: {
		width: "100%",
		minHeight: "80px",
		boxSizing: "border-box",
		...shorthands.padding("6px", "10px"),
		...shorthands.border("1px", "solid", tokens.colorNeutralStroke1),
		...shorthands.borderRadius(tokens.borderRadiusMedium),
		fontSize: tokens.fontSizeBase200,
		color: tokens.colorNeutralForeground1,
		backgroundColor: tokens.colorNeutralBackground1,
		outlineStyle: "none",
		fontFamily: "inherit",
		resize: "vertical" as const,
		"::placeholder": { color: tokens.colorNeutralForeground4 },
	},
	select: {
		width: "100%",
		boxSizing: "border-box",
		...shorthands.padding("8px", "30px", "8px", "10px"),
		...shorthands.border("1px", "solid", tokens.colorNeutralStroke1),
		...shorthands.borderRadius(tokens.borderRadiusMedium),
		fontSize: tokens.fontSizeBase200,
		color: tokens.colorNeutralForeground1,
		backgroundColor: tokens.colorNeutralBackground1,
		outlineStyle: "none",
		fontFamily: "inherit",
		appearance: "none",
		backgroundImage:
			'url("data:image/svg+xml,%3Csvg xmlns=%27http://www.w3.org/2000/svg%27 width=%2712%27 height=%2712%27 viewBox=%270 0 12 12%27%3E%3Cpath fill=%27%23616161%27 d=%27M2.22 4.47a.75.75 0 0 1 1.06 0L6 7.19l2.72-2.72a.75.75 0 1 1 1.06 1.06L6.53 8.78a.75.75 0 0 1-1.06 0L2.22 5.53a.75.75 0 0 1 0-1.06z%27/%3E%3C/svg%3E")',
		backgroundRepeat: "no-repeat",
		backgroundPosition: "right 10px center",
		cursor: "pointer",
		":disabled": {
			color: tokens.colorNeutralForeground4,
			backgroundColor: tokens.colorNeutralBackground3,
			cursor: "default",
		},
	},
	tagsInput: {
		display: "flex",
		alignItems: "center",
		flexWrap: "wrap",
		...shorthands.gap("6px"),
		minHeight: "34px",
		...shorthands.padding("6px", "10px"),
		...shorthands.border("1px", "solid", tokens.colorNeutralStroke1),
		...shorthands.borderRadius(tokens.borderRadiusMedium),
		backgroundColor: tokens.colorNeutralBackground1,
	},
	tagChip: {
		display: "inline-flex",
		alignItems: "center",
		...shorthands.gap("4px"),
		...shorthands.padding("2px", "8px"),
		...shorthands.borderRadius(tokens.borderRadiusCircular),
		backgroundColor: tokens.colorNeutralBackground3,
		color: tokens.colorNeutralForeground2,
		fontSize: tokens.fontSizeBase100,
	},
	tagRemove: {
		display: "inline-flex",
		alignItems: "center",
		justifyContent: "center",
		width: "14px",
		height: "14px",
		...shorthands.padding("0"),
		...shorthands.border("none"),
		backgroundColor: "transparent",
		color: tokens.colorNeutralForeground3,
		cursor: "pointer",
		":hover": { color: tokens.colorNeutralForeground1 },
	},
	tagInlineInput: {
		flex: 1,
		minWidth: "120px",
		...shorthands.padding("2px", "0"),
		...shorthands.border("none"),
		backgroundColor: "transparent",
		color: tokens.colorNeutralForeground1,
		fontSize: tokens.fontSizeBase200,
		outlineStyle: "none",
		fontFamily: "inherit",
		"::placeholder": { color: tokens.colorNeutralForeground4 },
	},
});
