import { makeStyles, shorthands, tokens } from "@fluentui/react-components";

const thinScrollbar = {
	scrollbarWidth: "thin" as const,
	scrollbarColor: `${tokens.colorNeutralForeground3} ${tokens.colorNeutralBackground3}`,
};

export const useStarterPromptsStyles = makeStyles({
	searchWrap: { position: "relative", width: "100%" },
	searchIcon: {
		position: "absolute",
		left: "8px",
		top: "50%",
		transform: "translateY(-50%)",
		color: tokens.colorNeutralForeground3,
		pointerEvents: "none",
	},
	searchInput: {
		width: "100%",
		boxSizing: "border-box",
		...shorthands.padding("6px", "10px", "6px", "28px"),
		...shorthands.border("1px", "solid", tokens.colorNeutralStroke1),
		...shorthands.borderRadius(tokens.borderRadiusMedium),
		fontSize: tokens.fontSizeBase200,
		color: tokens.colorNeutralForeground1,
		backgroundColor: tokens.colorNeutralBackground1,
		outlineStyle: "none",
		fontFamily: "inherit",
		"::placeholder": { color: tokens.colorNeutralForeground4 },
	},
	countText: {
		fontSize: tokens.fontSizeBase100,
		color: tokens.colorNeutralForeground3,
	},
	addButton: {
		minWidth: "auto",
		...shorthands.padding("4px", "10px"),
		...shorthands.border("none"),
		...shorthands.borderRadius(tokens.borderRadiusMedium),
		backgroundColor: tokens.colorBrandBackground,
		color: tokens.colorNeutralForegroundOnBrand,
		fontSize: tokens.fontSizeBase200,
		fontWeight: tokens.fontWeightSemibold,
		cursor: "pointer",
		display: "inline-flex",
		alignItems: "center",
		...shorthands.gap("4px"),
		":hover": { backgroundColor: tokens.colorBrandBackgroundHover },
	},
	list: {
		display: "flex",
		flexDirection: "column",
		flex: 1,
		minHeight: 0,
		overflowY: "auto",
		overflowX: "hidden",
		...shorthands.padding("0", "6px", "0", "12px"),
		...thinScrollbar,
	},
	row: {
		display: "flex",
		alignItems: "flex-start",
		justifyContent: "space-between",
		...shorthands.gap("10px"),
		...shorthands.padding("10px", "2px", "10px", "4px"),
		...shorthands.borderBottom("1px", "solid", tokens.colorNeutralStroke2),
		":last-child": { borderBottomStyle: "none" },
	},
	rowContent: { flex: 1, minWidth: 0 },
	rowTitleRow: {
		display: "flex",
		alignItems: "center",
		flexWrap: "wrap",
		...shorthands.gap("8px"),
	},
	rowTitle: {
		fontSize: tokens.fontSizeBase200,
		fontWeight: tokens.fontWeightSemibold,
		color: tokens.colorNeutralForeground1,
	},
	agentBadge: {
		display: "inline-flex",
		alignItems: "center",
		...shorthands.padding("1px", "6px"),
		...shorthands.borderRadius(tokens.borderRadiusCircular),
		backgroundColor: tokens.colorBrandBackground2,
		fontSize: tokens.fontSizeBase100,
		color: tokens.colorBrandForeground1,
	},
	rowPromptText: {
		marginTop: "4px",
		fontSize: tokens.fontSizeBase100,
		color: tokens.colorNeutralForeground3,
		whiteSpace: "nowrap",
		overflow: "hidden",
		textOverflow: "ellipsis",
	},
	rowActions: {
		display: "flex",
		alignItems: "center",
		...shorthands.gap("2px"),
		flexShrink: 0,
	},
	iconButton: {
		minWidth: "24px",
		width: "24px",
		height: "24px",
		...shorthands.padding("0"),
		...shorthands.border("none"),
		...shorthands.borderRadius("50%"),
		backgroundColor: "transparent",
		color: tokens.colorNeutralForeground3,
		cursor: "pointer",
		display: "inline-flex",
		alignItems: "center",
		justifyContent: "center",
		":hover": {
			backgroundColor: tokens.colorNeutralBackground1Hover,
			color: tokens.colorNeutralForeground1,
		},
		":disabled": { opacity: 0.4, cursor: "default" },
	},
	emptyState: {
		display: "flex",
		flexDirection: "column",
		alignItems: "center",
		justifyContent: "center",
		textAlign: "center",
		flex: 1,
		...shorthands.padding("32px", "16px"),
	},
	emptyIcon: {
		display: "inline-flex",
		alignItems: "center",
		justifyContent: "center",
		width: "48px",
		height: "48px",
		...shorthands.borderRadius(tokens.borderRadiusCircular),
		backgroundColor: tokens.colorNeutralBackground3,
		color: tokens.colorBrandForeground1,
	},
	emptyTitle: {
		marginTop: "12px",
		fontSize: tokens.fontSizeBase300,
		fontWeight: tokens.fontWeightSemibold,
		color: tokens.colorNeutralForeground1,
	},
	emptyDescription: {
		maxWidth: "320px",
		marginTop: "6px",
		fontSize: tokens.fontSizeBase200,
		color: tokens.colorNeutralForeground3,
		lineHeight: tokens.lineHeightBase300,
	},
	noService: {
		display: "flex",
		alignItems: "center",
		justifyContent: "center",
		flex: 1,
		color: tokens.colorNeutralForeground3,
		fontSize: tokens.fontSizeBase200,
	},
	dialogOverlay: {
		position: "absolute",
		inset: "0",
		display: "flex",
		alignItems: "center",
		justifyContent: "center",
		zIndex: 50,
		backgroundColor: "rgba(15, 23, 42, 0.25)",
	},
	dialog: {
		width: "min(380px, 90%)",
		backgroundColor: tokens.colorNeutralBackground1,
		...shorthands.borderRadius(tokens.borderRadiusLarge),
		boxShadow: tokens.shadow16,
		...shorthands.padding("20px"),
	},
	dialogTitle: {
		fontSize: tokens.fontSizeBase400,
		fontWeight: tokens.fontWeightSemibold,
		color: tokens.colorNeutralForeground1,
		marginBottom: "12px",
	},
	dialogText: {
		fontSize: tokens.fontSizeBase200,
		color: tokens.colorNeutralForeground2,
		lineHeight: tokens.lineHeightBase300,
		marginBottom: "16px",
	},
	dialogActions: {
		display: "flex",
		justifyContent: "flex-end",
		...shorthands.gap("8px"),
	},
	dialogButton: {
		...shorthands.padding("6px", "16px"),
		...shorthands.border("1px", "solid", tokens.colorNeutralStroke1),
		...shorthands.borderRadius(tokens.borderRadiusMedium),
		backgroundColor: "transparent",
		color: tokens.colorNeutralForeground1,
		fontSize: tokens.fontSizeBase200,
		fontWeight: tokens.fontWeightSemibold,
		cursor: "pointer",
		":hover": { backgroundColor: tokens.colorNeutralBackground1Hover },
		":disabled": { opacity: 0.5, cursor: "default" },
	},
	dialogButtonDanger: {
		backgroundColor: tokens.colorPaletteRedBackground3,
		color: tokens.colorNeutralForegroundOnBrand,
		...shorthands.borderColor(tokens.colorPaletteRedBackground3),
		":hover": { opacity: 0.9 },
	},
	errorBanner: {
		...shorthands.padding("8px", "10px"),
		...shorthands.borderRadius(tokens.borderRadiusMedium),
		backgroundColor: tokens.colorPaletteRedBackground1,
		color: tokens.colorPaletteRedForeground1,
		fontSize: tokens.fontSizeBase200,
		marginBottom: "8px",
	},
});
