import { makeStyles, shorthands, tokens } from "@fluentui/react-components";

export const useAIAssistantStyles = makeStyles({
	/* ── Root layout ── */
	root: {
		display: "flex",
		flexDirection: "column",
		flex: 1,
		height: "100%",
		width: "100%",
		minHeight: 0,
		position: "relative",
		backgroundColor: "var(--agent-chat-bg)",
		color: "var(--agent-chat-fg)",
		overflow: "hidden",
		...shorthands.borderLeft("1px", "solid", "var(--agent-chat-border)"),
		"@media (max-width: 768px)": {
			borderLeftWidth: 0,
		},
	},
	rootFullScreen: {
		position: "absolute",
		top: 0,
		left: 0,
		right: 0,
		bottom: 0,
		zIndex: 10,
		borderLeftWidth: 0,
	},
	/* ── Resize handle (side-panel only) ── */
	resizeHandle: {
		width: "6px",
		position: "absolute",
		left: "-4px",
		top: 0,
		bottom: 0,
		cursor: "col-resize",
		touchAction: "none",
		zIndex: 5,
		backgroundColor: "transparent",
		":before": {
			content: '""',
			position: "absolute",
			left: "50%",
			top: "50%",
			transform: "translate(-50%, -50%)",
			width: "2px",
			height: "36px",
			borderRadius: "999px",
			backgroundColor: "var(--agent-chat-border)",
			transitionProperty: "background-color",
			transitionDuration: "0.2s",
		},
		":hover:before": {
			backgroundColor: "var(--agent-chat-muted)",
		},
		"@media (max-width: 900px)": {
			display: "none",
		},
	},
	resizeHandleActive: {
		":before": {
			backgroundColor: "var(--agent-chat-brand)",
		},
	},
	immersiveLayout: {
		display: "flex",
		flexDirection: "row",
		flex: 1,
		minHeight: 0,
		overflow: "hidden",
	},
	contentBody: {
		flex: 1,
		display: "flex",
		flexDirection: "column",
		minWidth: 0,
		minHeight: 0,
		height: "100%",
		overflow: "hidden",
	},

	/* ── Sidebar (full-screen only) ── */
	sidebar: {
		display: "flex",
		flexDirection: "column",
		height: "100%",
		backgroundColor: "var(--agent-chat-sidebar-bg, var(--agent-chat-bg))",
		...shorthands.borderRight("1px", "solid", "var(--agent-chat-border)"),
		boxSizing: "border-box",
		flexShrink: 0,
		transitionProperty: "width",
		transitionDuration: "0.2s",
		transitionTimingFunction: "ease",
		overflow: "hidden",
	},
	sidebarExpanded: {
		width: "260px",
	},
	sidebarCollapsed: {
		width: "44px",
	},
	sidebarTopBar: {
		display: "flex",
		alignItems: "center",
		justifyContent: "center",
		height: "42px",
		...shorthands.padding("0", "6px"),
		boxSizing: "border-box",
		flexShrink: 0,
	},
	sidebarTopBarExpanded: {
		justifyContent: "space-between",
	},
	sidebarToggle: {
		minWidth: "32px",
		width: "32px",
		height: "32px",
		...shorthands.border("none"),
		...shorthands.borderRadius("8px"),
		...shorthands.padding("0"),
		display: "inline-flex",
		alignItems: "center",
		justifyContent: "center",
		backgroundColor: "transparent",
		color: "var(--agent-chat-muted)",
		cursor: "pointer",
		":hover": {
			backgroundColor: "var(--agent-chat-hover)",
			color: "var(--agent-chat-fg)",
		},
	},
	sidebarNav: {
		display: "flex",
		flexDirection: "column",
		...shorthands.gap("2px"),
		...shorthands.padding("4px", "6px"),
		flexShrink: 0,
		overflowX: "hidden",
	},
	sidebarNavButton: {
		display: "flex",
		alignItems: "center",
		justifyContent: "center",
		...shorthands.gap("10px"),
		...shorthands.padding("8px"),
		...shorthands.border("none"),
		...shorthands.borderRadius("10px"),
		backgroundColor: "transparent",
		color: "var(--agent-chat-fg)",
		cursor: "pointer",
		fontSize: tokens.fontSizeBase200,
		fontWeight: tokens.fontWeightRegular,
		whiteSpace: "nowrap",
		overflow: "hidden",
		minHeight: "36px",
		":hover": {
			backgroundColor: "var(--agent-chat-hover)",
		},
	},
	sidebarNavButtonExpanded: {
		justifyContent: "flex-start",
		...shorthands.padding("8px", "10px"),
	},
	sidebarNavButtonActive: {
		backgroundColor: "var(--agent-chat-hover)",
		fontWeight: tokens.fontWeightSemibold,
		boxShadow: "inset 0 0 0 1px var(--agent-chat-border)",
	},
	sidebarNavIcon: {
		flexShrink: 0,
		display: "inline-flex",
		alignItems: "center",
		justifyContent: "center",
		width: "20px",
		height: "20px",
		color: "var(--agent-chat-muted)",
	},
	sidebarNavLabel: {
		overflow: "hidden",
		textOverflow: "ellipsis",
	},

	/* ── Header bar ── */
	header: {
		display: "flex",
		alignItems: "center",
		justifyContent: "space-between",
		height: "42px",
		...shorthands.borderBottom("1px", "solid", "var(--agent-chat-border)"),
		...shorthands.padding("0", "8px"),
		boxSizing: "border-box",
		flexShrink: 0,
	},
	headerTitle: {
		fontSize: tokens.fontSizeBase300,
		fontWeight: tokens.fontWeightSemibold,
		color: "var(--agent-chat-fg)",
		whiteSpace: "nowrap",
		overflow: "hidden",
		textOverflow: "ellipsis",
		minWidth: 0,
		marginLeft: "4px",
	},
	headerActions: {
		display: "flex",
		alignItems: "center",
		...shorthands.gap("2px"),
	},
	headerButton: {
		minWidth: "34px",
		width: "34px",
		height: "34px",
		...shorthands.border("none"),
		...shorthands.borderRadius("50%"),
		...shorthands.padding("0"),
		display: "inline-flex",
		alignItems: "center",
		justifyContent: "center",
		backgroundColor: "transparent",
		color: "var(--agent-chat-muted)",
		cursor: "pointer",
		":hover": {
			backgroundColor: "var(--agent-chat-hover)",
			color: "var(--agent-chat-fg)",
		},
	},
	headerButtonActive: {
		backgroundColor: "var(--agent-chat-hover)",
		color: "var(--agent-chat-brand)",
	},
	headerButtonHideMobile: {
		"@media (max-width: 768px)": {
			display: "none",
		},
	},

	/* ── Welcome screen ── */
	welcomeContainer: {
		flex: 1,
		width: "100%",
		display: "flex",
		flexDirection: "column",
		alignItems: "center",
		boxSizing: "border-box",
		overflow: "hidden",
	},
	welcomeCenter: {
		flex: 1,
		display: "flex",
		flexDirection: "column",
		alignItems: "center",
		justifyContent: "center",
		...shorthands.gap("20px"),
		...shorthands.padding("24px", "16px"),
		width: "100%",
		boxSizing: "border-box",
	},
	welcomeIcon: {
		color: "var(--agent-chat-brand)",
		opacity: 0.85,
	},
	welcomeHeading: {
		marginTop: 0,
		marginBottom: 0,
		textAlign: "center",
		fontSize: "28px",
		lineHeight: "1.25",
		fontWeight: tokens.fontWeightRegular,
		color: "var(--agent-chat-muted)",
		letterSpacing: "-0.01em",
		"@media (max-width: 640px)": {
			fontSize: "22px",
		},
	},
	welcomeHeadingFullScreen: {
		fontSize: "38px",
		"@media (max-width: 900px)": {
			fontSize: "30px",
		},
	},
	welcomeHeadingStrong: {
		fontWeight: tokens.fontWeightSemibold,
		color: "var(--agent-chat-fg)",
		marginRight: "8px",
	},
	welcomeComposer: {
		width: "100%",
		maxWidth: "640px",
		display: "flex",
		flexDirection: "column",
		alignItems: "center",
		...shorthands.gap("14px"),
		marginTop: "8px",
	},
	welcomeComposerFullScreen: {
		maxWidth: "780px",
	},
});
