import { makeStyles, shorthands, tokens } from "@fluentui/react-components";

export const useChatInputStyles = makeStyles({
	wrapper: {
		position: "relative" as const,
		width: "100%",
		maxWidth: "920px",
		alignSelf: "center",
		...shorthands.padding("0", "8px", "16px"),
		boxSizing: "border-box",
		flexShrink: 0,
	},
	composer: {
		display: "flex",
		flexDirection: "column",
		...shorthands.border("1px", "solid", "var(--agent-chat-border)"),
		...shorthands.borderRadius("16px"),
		backgroundColor: "var(--agent-chat-card)",
		...shorthands.padding("12px", "12px", "8px"),
		boxShadow: tokens.shadow4,
	},
	textarea: {
		width: "100%",
		border: "none",
		outlineStyle: "none",
		resize: "none" as const,
		backgroundColor: "transparent",
		color: "var(--agent-chat-fg)",
		fontFamily: tokens.fontFamilyBase,
		fontSize: tokens.fontSizeBase300,
		lineHeight: tokens.lineHeightBase300,
		minHeight: "28px",
		maxHeight: "120px",
		paddingRight: "4px",
		"::placeholder": {
			color: "var(--agent-chat-muted)",
		},
	},
	footer: {
		display: "flex",
		alignItems: "center",
		justifyContent: "space-between",
		...shorthands.gap("8px"),
	},
	leftTools: {
		display: "flex",
		alignItems: "center",
		...shorthands.gap("4px"),
		minWidth: 0,
	},
	modelButton: {
		display: "inline-flex",
		alignItems: "center",
		...shorthands.gap("5px"),
		...shorthands.padding("2px", "8px"),
		...shorthands.borderRadius("10px"),
		color: "var(--agent-chat-muted)",
		fontSize: tokens.fontSizeBase200,
		backgroundColor: "transparent",
		...shorthands.border("none"),
		cursor: "pointer",
		":hover": {
			backgroundColor: "var(--agent-chat-hover)",
			color: "var(--agent-chat-fg)",
		},
	},
	rightTools: {
		display: "flex",
		alignItems: "center",
		...shorthands.gap("6px"),
	},
	iconButton: {
		minWidth: "34px",
		width: "34px",
		height: "34px",
		...shorthands.borderRadius("50%"),
		...shorthands.padding("0"),
		...shorthands.border("none"),
		backgroundColor: "transparent",
		color: "var(--agent-chat-muted)",
		cursor: "pointer",
		display: "inline-flex",
		alignItems: "center",
		justifyContent: "center",
		":hover": {
			backgroundColor: "var(--agent-chat-hover)",
			color: "var(--agent-chat-fg)",
		},
	},
	sendButton: {
		minWidth: "36px",
		width: "36px",
		height: "36px",
		...shorthands.borderRadius("50%"),
		...shorthands.padding("0"),
		...shorthands.border("none"),
		backgroundColor: "transparent",
		color: "var(--agent-chat-muted)",
		cursor: "pointer",
		display: "inline-flex",
		alignItems: "center",
		justifyContent: "center",
	},
	sendButtonActive: {
		color: "#ffffff",
		backgroundColor: "var(--agent-chat-brand)",
		":hover": {
			backgroundColor: "#0c5da5",
			color: "#ffffff",
		},
	},
	stopButton: {
		color: "#ffffff",
		backgroundColor: "var(--agent-chat-brand)",
		":hover": {
			backgroundColor: "#0c5da5",
			color: "#ffffff",
		},
	},

	/* ── Autocomplete suggestions dropdown ── */
	suggestionsDropdown: {
		position: "absolute" as const,
		bottom: "100%",
		left: tokens.spacingHorizontalL,
		right: tokens.spacingHorizontalL,
		backgroundColor: tokens.colorNeutralBackground1,
		...shorthands.borderRadius("10px"),
		...shorthands.border("1px", "solid", tokens.colorNeutralStroke2),
		boxShadow: tokens.shadow16,
		maxHeight: "220px",
		overflowY: "auto" as const,
		marginBottom: tokens.spacingVerticalXS,
		zIndex: 10,
		...shorthands.padding("4px", "0"),
	},
	suggestionItem: {
		display: "flex",
		flexDirection: "column" as const,
		alignItems: "flex-start",
		width: "100%",
		...shorthands.padding("6px", "14px"),
		border: "none",
		borderBottomWidth: "1px",
		borderBottomStyle: "solid",
		borderBottomColor: tokens.colorNeutralStroke2,
		backgroundColor: "transparent",
		cursor: "pointer",
		textAlign: "left" as const,
		fontFamily: "inherit",
		transitionProperty: "background-color",
		transitionDuration: "0.15s",
		transitionTimingFunction: "ease",
		":hover": {
			backgroundColor: tokens.colorNeutralBackground1Hover,
		},
		":last-child": {
			borderBottomWidth: "0",
		},
	},
	suggestionItemActive: {
		backgroundColor: tokens.colorNeutralBackground1Hover,
	},
	suggestionTitle: {
		fontSize: tokens.fontSizeBase300,
		fontWeight: tokens.fontWeightSemibold,
		color: tokens.colorNeutralForeground1,
		lineHeight: tokens.lineHeightBase300,
	},
	suggestionPrompt: {
		fontSize: tokens.fontSizeBase200,
		color: tokens.colorNeutralForeground3,
		marginTop: "1px",
		whiteSpace: "nowrap" as const,
		overflow: "hidden" as const,
		textOverflow: "ellipsis" as const,
		maxWidth: "100%",
		lineHeight: tokens.lineHeightBase100,
	},
});
