import { makeStyles, shorthands, tokens } from "@fluentui/react-components";

export const usePageLayoutStyles = makeStyles({
	root: {
		position: "relative",
		display: "flex",
		flexDirection: "column",
		height: "100%",
		minHeight: 0,
		boxSizing: "border-box",
		overflow: "hidden",
		backgroundColor: tokens.colorNeutralBackground1,
	},
	header: {
		display: "flex",
		alignItems: "center",
		justifyContent: "space-between",
		minHeight: "42px",
		flexWrap: "nowrap",
		...shorthands.padding("0", "12px"),
		...shorthands.borderBottom("1px", "solid", tokens.colorNeutralStroke2),
		backgroundColor: tokens.colorNeutralBackground1,
		boxSizing: "border-box",
		flexShrink: 0,
	},
	titleGroup: {
		minWidth: 0,
		flex: 1,
	},
	title: {
		fontSize: tokens.fontSizeBase300,
		fontWeight: tokens.fontWeightSemibold,
		lineHeight: tokens.lineHeightBase300,
		color: tokens.colorNeutralForeground1,
	},
	actions: {
		display: "flex",
		alignItems: "center",
		justifyContent: "flex-end",
		...shorthands.gap("4px"),
		flexShrink: 0,
	},
	closeButton: {
		minWidth: "28px",
		width: "28px",
		height: "28px",
		...shorthands.border("none"),
		...shorthands.borderRadius("50%"),
		...shorthands.padding("0"),
		display: "inline-flex",
		alignItems: "center",
		justifyContent: "center",
		backgroundColor: "transparent",
		color: tokens.colorNeutralForeground3,
		cursor: "pointer",
		flexShrink: 0,
		":hover": {
			backgroundColor: tokens.colorNeutralBackground1Hover,
			color: tokens.colorNeutralForeground1,
		},
	},
	toolbar: {
		display: "flex",
		flexDirection: "column",
		alignItems: "stretch",
		width: "100%",
		...shorthands.padding("8px", "12px", "6px"),
		...shorthands.gap("8px"),
		boxSizing: "border-box",
	},
	content: {
		display: "flex",
		flexDirection: "column",
		flex: 1,
		minHeight: 0,
		width: "100%",
		overflow: "hidden",
	},
});
