import { makeStyles, shorthands, tokens } from "@fluentui/react-components";

export const useSidebarChatHistoryStyles = makeStyles({
	section: {
		display: "flex",
		flexDirection: "column",
		flex: 1,
		minHeight: 0,
		...shorthands.borderTop("1px", "solid", "var(--agent-chat-border)"),
		marginTop: "4px",
	},
	searchWrap: {
		position: "relative",
		...shorthands.padding("8px", "8px", "4px"),
		flexShrink: 0,
	},
	searchIcon: {
		position: "absolute",
		left: "14px",
		top: "calc(50% + 2px)",
		transform: "translateY(-50%)",
		color: "var(--agent-chat-muted)",
		pointerEvents: "none",
		fontSize: "12px",
	},
	searchInput: {
		width: "100%",
		boxSizing: "border-box",
		...shorthands.padding("5px", "8px", "5px", "26px"),
		...shorthands.border("1px", "solid", "var(--agent-chat-border)"),
		...shorthands.borderRadius("6px"),
		fontSize: tokens.fontSizeBase100,
		color: "var(--agent-chat-fg)",
		backgroundColor: "var(--agent-chat-surface)",
		outlineStyle: "none",
		fontFamily: "inherit",
		"::placeholder": { color: "var(--agent-chat-muted)" },
	},
	list: {
		flex: 1,
		overflowY: "auto",
		overflowX: "hidden",
		...shorthands.padding("0", "4px"),
		display: "flex",
		flexDirection: "column",
		scrollbarWidth: "thin" as const,
	},
	group: {
		display: "flex",
		flexDirection: "column",
		marginBottom: "2px",
	},
	groupLabel: {
		fontSize: "10px",
		fontWeight: tokens.fontWeightSemibold,
		color: "var(--agent-chat-muted)",
		textTransform: "uppercase",
		letterSpacing: "0.5px",
		...shorthands.padding("8px", "8px", "2px"),
	},
	item: {
		display: "flex",
		alignItems: "center",
		width: "100%",
		...shorthands.gap("8px"),
		...shorthands.padding("7px", "10px"),
		...shorthands.border("1px", "solid", "transparent"),
		...shorthands.borderRadius("10px"),
		backgroundColor: "transparent",
		color: "var(--agent-chat-fg)",
		cursor: "pointer",
		fontSize: tokens.fontSizeBase200,
		fontFamily: "inherit",
		textAlign: "left" as const,
		minHeight: "32px",
		boxSizing: "border-box",
		borderLeftWidth: "3px",
		borderLeftStyle: "solid",
		borderLeftColor: "transparent",
		transitionProperty: "background-color, border-color, box-shadow",
		transitionDuration: "0.15s",
		":hover": {
			backgroundColor: "var(--agent-chat-hover)",
			...shorthands.border("1px", "solid", "var(--agent-chat-border)"),
			borderLeftWidth: "3px",
			borderLeftColor: "transparent",
			boxShadow: "0 1px 3px rgba(0,0,0,0.06)",
		},
	},
	itemActive: {
		backgroundColor: "var(--agent-chat-surface)",
		borderLeftColor: tokens.colorBrandBackground,
		fontWeight: tokens.fontWeightSemibold,
		...shorthands.border("1px", "solid", "var(--agent-chat-border)"),
		borderLeftWidth: "3px",
		":hover": {
			backgroundColor: "var(--agent-chat-surface)",
			borderLeftColor: tokens.colorBrandBackground,
			boxShadow: "none",
		},
	},
	itemText: {
		flex: 1,
		minWidth: 0,
		whiteSpace: "nowrap",
		overflow: "hidden",
		textOverflow: "ellipsis",
		fontSize: tokens.fontSizeBase200,
		fontWeight: tokens.fontWeightRegular,
	},
	itemTime: {
		flexShrink: 0,
		fontSize: "10px",
		color: "var(--agent-chat-muted)",
		fontWeight: tokens.fontWeightRegular,
	},
	empty: {
		...shorthands.padding("16px", "10px"),
		fontSize: tokens.fontSizeBase100,
		color: "var(--agent-chat-muted)",
		textAlign: "center" as const,
	},
});
