import { makeStyles, shorthands, tokens } from "@fluentui/react-components";

export const useSidebarChatHistoryStyles = makeStyles({
	section: {
		display: "flex",
		flexDirection: "column",
		flex: 1,
		minHeight: 0,
		...shorthands.borderTop("1px", "solid", "var(--agent-chat-border)"),
		marginTop: "4px",
	},
	header: {
		display: "flex",
		alignItems: "center",
		justifyContent: "space-between",
		...shorthands.padding("8px", "10px", "4px"),
		flexShrink: 0,
	},
	title: {
		fontSize: tokens.fontSizeBase100,
		fontWeight: tokens.fontWeightSemibold,
		color: "var(--agent-chat-muted)",
		textTransform: "uppercase",
		letterSpacing: "0.04em",
	},
	searchWrap: {
		position: "relative",
		...shorthands.padding("0", "8px", "6px"),
		flexShrink: 0,
	},
	searchIcon: {
		position: "absolute",
		left: "14px",
		top: "calc(50% - 3px)",
		transform: "translateY(-50%)",
		color: "var(--agent-chat-muted)",
		pointerEvents: "none",
		fontSize: "12px",
	},
	searchInput: {
		width: "100%",
		boxSizing: "border-box",
		...shorthands.padding("5px", "8px", "5px", "26px"),
		...shorthands.border("1px", "solid", "var(--agent-chat-border)"),
		...shorthands.borderRadius("6px"),
		fontSize: tokens.fontSizeBase100,
		color: "var(--agent-chat-fg)",
		backgroundColor: "var(--agent-chat-surface)",
		outlineStyle: "none",
		fontFamily: "inherit",
		"::placeholder": { color: "var(--agent-chat-muted)" },
	},
	list: {
		flex: 1,
		overflowY: "auto",
		overflowX: "hidden",
		...shorthands.padding("0", "6px"),
		scrollbarWidth: "thin" as const,
	},
	item: {
		display: "flex",
		alignItems: "center",
		width: "100%",
		...shorthands.padding("7px", "8px"),
		...shorthands.border("none"),
		...shorthands.borderRadius("8px"),
		backgroundColor: "transparent",
		color: "var(--agent-chat-fg)",
		cursor: "pointer",
		fontSize: tokens.fontSizeBase200,
		fontFamily: "inherit",
		textAlign: "left" as const,
		whiteSpace: "nowrap",
		overflow: "hidden",
		textOverflow: "ellipsis",
		minHeight: "32px",
		boxSizing: "border-box",
		":hover": {
			backgroundColor: "var(--agent-chat-hover)",
		},
	},
	empty: {
		...shorthands.padding("16px", "10px"),
		fontSize: tokens.fontSizeBase100,
		color: "var(--agent-chat-muted)",
		textAlign: "center" as const,
	},
});
