import { makeStyles, shorthands, tokens } from "@fluentui/react-components";

export const useMessageRendererStyles = makeStyles({
	assistantBlock: {
		display: "flex",
		flexDirection: "column",
		alignItems: "flex-start",
		...shorthands.gap("6px"),
	},
	assistantPreamble: {
		display: "flex",
		alignItems: "center",
		...shorthands.gap("8px"),
		color: "var(--agent-chat-muted)",
		fontSize: tokens.fontSizeBase100,
	},
	avatar: {
		width: "32px",
		height: "32px",
		borderRadius: "50%",
		display: "flex",
		alignItems: "center",
		justifyContent: "center",
		backgroundImage: "linear-gradient(135deg, #3367d6 0%, #5f4dd0 100%)",
		color: "#ffffff",
		flexShrink: 0,
	},
	cancelledMessage: {
		marginLeft: "32px",
		color: tokens.colorPaletteRedForeground1,
		fontSize: "0.88rem",
		lineHeight: "1.5",
	},
	assistantCard: {
		width: "calc(100% - 32px)",
		marginLeft: "32px",
		backgroundColor: "var(--agent-chat-card)",
		...shorthands.border("1px", "solid", "var(--agent-chat-border)"),
		...shorthands.borderRadius("10px"),
		...shorthands.padding("10px"),
		boxSizing: "border-box",
	},
	localAssistantRichContent: {
		width: "100%",
		maxWidth: "100%",
		minWidth: 0,
	},
	generatedAssistantHtml: {
		width: "100%",
		maxWidth: "100%",
		minWidth: 0,
		overflowX: "auto",
	},
	localAssistantBubble: {
		maxWidth: "calc(78% - 32px)",
		marginLeft: "32px",
		backgroundColor: "var(--agent-chat-surface)",
		color: "var(--agent-chat-fg)",
		...shorthands.border("1px", "solid", "var(--agent-chat-border)"),
		...shorthands.borderRadius("10px"),
		...shorthands.padding("10px", "14px"),
		fontSize: tokens.fontSizeBase200,
		lineHeight: tokens.lineHeightBase200,
	},
	rawJsonCard: {
		width: "calc(100% - 32px)",
		marginLeft: "32px",
		backgroundColor: "var(--agent-chat-card)",
		...shorthands.border("1px", "solid", "var(--agent-chat-border)"),
		...shorthands.borderRadius("10px"),
		...shorthands.padding("0px"),
		boxSizing: "border-box" as const,
		display: "flex",
		flexDirection: "column" as const,
	},
	rawJsonHeader: {
		display: "flex",
		alignItems: "center",
		justifyContent: "space-between",
		...shorthands.padding("6px", "12px"),
		...shorthands.borderBottom("1px", "solid", "var(--agent-chat-border)"),
		fontSize: tokens.fontSizeBase100,
		color: "var(--agent-chat-muted)",
	},
	rawJsonCopyButton: {
		display: "inline-flex",
		alignItems: "center",
		justifyContent: "center",
		...shorthands.gap("4px"),
		...shorthands.border("none"),
		...shorthands.borderRadius("4px"),
		...shorthands.padding("2px", "8px"),
		backgroundColor: "transparent",
		color: "var(--agent-chat-muted)",
		cursor: "pointer",
		fontSize: tokens.fontSizeBase100,
		":hover": {
			backgroundColor: "var(--agent-chat-border)",
		},
	},
	rawJsonPre: {
		margin: 0,
		whiteSpace: "pre-wrap" as const,
		wordBreak: "break-word" as const,
		fontFamily: tokens.fontFamilyMonospace,
		fontSize: tokens.fontSizeBase200,
		lineHeight: tokens.lineHeightBase200,
		color: "var(--agent-chat-fg)",
		...shorthands.padding("12px"),
		overflowX: "auto" as const,
		maxHeight: "500px",
		overflowY: "auto" as const,
	},
	shimmerColumn: {
		display: "flex",
		flexDirection: "column",
		...shorthands.gap("12px"),
	},
	shimmerRow: {
		display: "flex",
		...shorthands.gap("10px"),
		marginTop: "4px",
	},
});
