import { makeStyles, shorthands, tokens } from "@fluentui/react-components";

const thinScrollbar = {
	scrollbarWidth: "thin" as const,
	scrollbarColor: `${tokens.colorNeutralForeground3} ${tokens.colorNeutralBackground3}`,
};

export const useSlidePanelStyles = makeStyles({
	layer: {
		position: "absolute",
		inset: "0",
		display: "flex",
		justifyContent: "flex-end",
		zIndex: 40,
	},
	backdrop: {
		position: "absolute",
		inset: "0",
		backgroundColor: "rgba(15, 23, 42, 0.18)",
		backdropFilter: "blur(2px)",
	},
	panel: {
		position: "relative",
		display: "flex",
		flexDirection: "column",
		width: "90%",
		height: "100%",
		backgroundColor: tokens.colorNeutralBackground1,
		boxShadow: tokens.shadow16,
	},
	header: {
		display: "flex",
		alignItems: "center",
		justifyContent: "space-between",
		...shorthands.gap("8px"),
		...shorthands.padding("6px", "12px"),
		...shorthands.borderBottom("1px", "solid", tokens.colorNeutralStroke2),
		flexShrink: 0,
	},
	titleRow: {
		display: "flex",
		alignItems: "center",
		...shorthands.gap("8px"),
		minWidth: 0,
		flex: 1,
	},
	titleIcon: {
		color: tokens.colorBrandForeground1,
		fontSize: "16px",
		flexShrink: 0,
	},
	title: {
		fontSize: tokens.fontSizeBase300,
		fontWeight: tokens.fontWeightSemibold,
		color: tokens.colorNeutralForeground1,
	},
	closeButton: {
		minWidth: "28px",
		width: "28px",
		height: "28px",
		...shorthands.border("none"),
		...shorthands.borderRadius("50%"),
		...shorthands.padding("0"),
		display: "inline-flex",
		alignItems: "center",
		justifyContent: "center",
		backgroundColor: "transparent",
		color: tokens.colorNeutralForeground3,
		cursor: "pointer",
		":hover": {
			backgroundColor: tokens.colorNeutralBackground1Hover,
			color: tokens.colorNeutralForeground1,
		},
	},
	body: {
		position: "relative",
		display: "flex",
		flexDirection: "column",
		flex: 1,
		minHeight: 0,
		overflowY: "auto",
		...shorthands.padding("12px", "12px", "16px"),
		...shorthands.gap("14px"),
		...thinScrollbar,
	},
	footer: {
		display: "flex",
		alignItems: "center",
		justifyContent: "flex-start",
		...shorthands.gap("8px"),
		...shorthands.padding("8px", "12px"),
		...shorthands.borderTop("1px", "solid", tokens.colorNeutralStroke2),
		backgroundColor: tokens.colorNeutralBackground1,
	},
	primaryButton: {
		minWidth: "72px",
		...shorthands.padding("4px", "12px"),
		...shorthands.border("none"),
		...shorthands.borderRadius(tokens.borderRadiusMedium),
		backgroundColor: tokens.colorBrandBackground,
		color: tokens.colorNeutralForegroundOnBrand,
		fontWeight: tokens.fontWeightSemibold,
		fontSize: tokens.fontSizeBase200,
		cursor: "pointer",
		":hover": { backgroundColor: tokens.colorBrandBackgroundHover },
		":disabled": { opacity: 0.5, cursor: "default" },
	},
	secondaryButton: {
		minWidth: "72px",
		...shorthands.padding("4px", "12px"),
		...shorthands.border("1px", "solid", tokens.colorNeutralStroke1),
		...shorthands.borderRadius(tokens.borderRadiusMedium),
		backgroundColor: "transparent",
		color: tokens.colorNeutralForeground1,
		fontWeight: tokens.fontWeightSemibold,
		fontSize: tokens.fontSizeBase200,
		cursor: "pointer",
		":hover": { backgroundColor: tokens.colorNeutralBackground1Hover },
		":disabled": { opacity: 0.5, cursor: "default" },
	},
	errorBanner: {
		marginBottom: "4px",
		...shorthands.padding("8px", "10px"),
		...shorthands.borderRadius(tokens.borderRadiusMedium),
		backgroundColor: tokens.colorPaletteRedBackground1,
		color: tokens.colorPaletteRedForeground1,
		fontSize: tokens.fontSizeBase200,
		lineHeight: tokens.lineHeightBase200,
	},
});
