import { makeStyles, shorthands, tokens } from "@fluentui/react-components";

const typingBounce = {
	"0%, 80%, 100%": {
		transform: "scale(0.6)",
		opacity: "0.5",
	},
	"40%": {
		transform: "scale(1)",
		opacity: "1",
	},
};

const shimmer = {
	"0%": { backgroundPosition: "200% 0" },
	"100%": { backgroundPosition: "-200% 0" },
};

export const useAIAssistantChatStyles = makeStyles({
	immersiveLayout: {
		display: "flex",
		height: "100%",
		width: "100%",
		overflow: "hidden",
	},
	contentArea: {
		flex: 1,
		display: "flex",
		flexDirection: "column",
		position: "relative",
		minWidth: 0,
		minHeight: 0,
		height: "100%",
		overflow: "hidden",
	},
	contentBody: {
		flex: 1,
		display: "flex",
		flexDirection: "column",
		minWidth: 0,
		minHeight: 0,
		height: "100%",
		overflow: "hidden",
	},
	sidePanelLayout: {
		display: "flex",
		height: "100%",
		width: "100%",
		overflow: "hidden",
		backgroundColor: "var(--agent-chat-bg)",
		justifyContent: "flex-end",
	},
	sidePanelStage: {
		flex: 1,
		minWidth: 0,
		backgroundColor: "var(--agent-chat-bg)",
	},
	sidePanelDrawer: {
		display: "flex",
		height: "100%",
		width: "var(--agent-chat-sidepanel-width, 560px)",
		maxWidth: "100%",
		flexShrink: 0,
		minWidth: 0,
		transition: "width 0.2s ease",
		boxSizing: "border-box",
	},
	sidePanelDrawerResizing: {
		transition: "none",
	},
	sidePanelDrawerExpanded: {
		width: "min(920px, 100%)",
	},
	sidePanelResizeHandle: {
		width: "10px",
		height: "100%",
		flexShrink: 0,
		cursor: "col-resize",
		touchAction: "none",
		position: "relative",
		backgroundColor: "transparent",
		":before": {
			content: '""',
			position: "absolute",
			left: "50%",
			top: "50%",
			transform: "translate(-50%, -50%)",
			width: "2px",
			height: "36px",
			borderRadius: "999px",
			backgroundColor: "var(--agent-chat-border)",
			transition: "background-color 0.2s ease",
		},
		":hover:before": {
			backgroundColor: "var(--agent-chat-muted)",
		},
		"@media (max-width: 900px)": {
			display: "none",
		},
	},
	sidePanelResizeHandleActive: {
		":before": {
			backgroundColor: "var(--agent-chat-brand)",
		},
	},
	sidePanelChatColumn: {
		display: "flex",
		flexDirection: "column",
		flex: 1,
		minWidth: 0,
		minHeight: 0,
		height: "100%",
		overflow: "hidden",
	},
	sidePanelAuxiliary: {
		width: "360px",
		minWidth: "360px",
		maxWidth: "360px",
		height: "100%",
		...shorthands.borderLeft("1px", "solid", "var(--agent-chat-border)"),
		backgroundColor: "var(--agent-chat-surface)",
		overflow: "hidden",
		display: "flex",
		flexDirection: "column",
	},
	sidePanelAuxiliaryBody: {
		flex: 1,
		minHeight: 0,
		overflow: "hidden",
	},
	sidePanelAuxiliaryChats: {
		backgroundColor: "var(--agent-chat-surface)",
	},
	sidePanelAuxiliaryStarterPrompts: {
		backgroundColor: tokens.colorNeutralBackground1,
	},
	sidePanelAuxiliarySettings: {
		backgroundColor: "var(--agent-chat-surface)",
	},
	sidePanelHeaderButton: {
		minWidth: "34px",
		width: "34px",
		height: "34px",
		...shorthands.border("none"),
		...shorthands.borderRadius("50%"),
		...shorthands.padding("0"),
		display: "inline-flex",
		alignItems: "center",
		justifyContent: "center",
		backgroundColor: "transparent",
		color: "var(--agent-chat-muted)",
		cursor: "pointer",
		":hover": {
			backgroundColor: "var(--agent-chat-hover)",
			color: "var(--agent-chat-fg)",
		},
	},
	sidePanelHeaderButtonActive: {
		backgroundColor: "var(--agent-chat-hover)",
		color: "var(--agent-chat-fg)",
	},
	immersiveHeaderBar: {
		display: "flex",
		alignItems: "center",
		justifyContent: "space-between",
		height: "42px",
		...shorthands.borderBottom("1px", "solid", "var(--agent-chat-border)"),
		...shorthands.padding("0", "8px"),
		boxSizing: "border-box",
		flexShrink: 0,
	},
	root: {
		display: "flex",
		flexDirection: "column",
		flex: 1,
		height: "100%",
		minHeight: 0,
		backgroundColor: "var(--agent-chat-bg)",
		color: "var(--agent-chat-fg)",
		overflow: "hidden",
	},
	rootSidePanel: {
		...shorthands.borderLeft("1px", "solid", "var(--agent-chat-border)"),
		backgroundColor: "var(--agent-chat-surface)",
	},
	rootImmersive: {
		width: "100%",
	},

	panelHeader: {
		display: "flex",
		alignItems: "center",
		justifyContent: "space-between",
		height: "42px",
		...shorthands.borderBottom("1px", "solid", "var(--agent-chat-border)"),
		...shorthands.padding("0", "8px"),
		boxSizing: "border-box",
		flexShrink: 0,
	},
	panelHeaderTitle: {
		fontSize: tokens.fontSizeBase300,
		fontWeight: tokens.fontWeightSemibold,
		color: "var(--agent-chat-fg)",
		whiteSpace: "nowrap",
		overflow: "hidden",
		textOverflow: "ellipsis",
		minWidth: 0,
		marginLeft: "4px",
	},
	immersiveHeader: {
		display: "flex",
		alignItems: "center",
		justifyContent: "space-between",
		...shorthands.padding("8px", "16px"),
		boxSizing: "border-box",
		flexShrink: 0,
	},
	immersiveHeaderLeft: {
		display: "flex",
		alignItems: "center",
		...shorthands.gap("6px"),
	},
	immersiveHeaderTitle: {
		fontSize: tokens.fontSizeBase300,
		color: "var(--agent-chat-muted)",
		whiteSpace: "nowrap",
		overflow: "hidden",
		textOverflow: "ellipsis",
		maxWidth: "55%",
	},
	immersiveHeaderSpacer: {
		width: "18px",
		flexShrink: 0,
	},
	headerActions: {
		display: "flex",
		alignItems: "center",
		...shorthands.gap("2px"),
	},
	iconButton: {
		minWidth: "34px",
		width: "34px",
		height: "34px",
		...shorthands.borderRadius("50%"),
		...shorthands.padding("0"),
		color: "var(--agent-chat-muted)",
		":hover": {
			backgroundColor: "var(--agent-chat-hover)",
			color: "var(--agent-chat-fg)",
		},
	},

	thread: {
		flex: 1,
		minHeight: 0,
		overflowY: "auto",
		overflowX: "hidden",
		width: "100%",
		maxWidth: "920px",
		alignSelf: "center",
		...shorthands.padding("14px", "18px", "10px"),
		boxSizing: "border-box",
		display: "flex",
		flexDirection: "column",
		...shorthands.gap("14px"),
	},
	chatLoader: {
		flex: 1,
		display: "flex",
		alignItems: "center",
		justifyContent: "center",
	},
	welcomeContainer: {
		flex: 1,
		width: "100%",
		display: "flex",
		flexDirection: "column",
		alignItems: "center",
		justifyContent: "center",
		...shorthands.gap("24px"),
		...shorthands.padding("24px", "16px", "32px"),
		boxSizing: "border-box",
	},
	welcomeHeading: {
		marginTop: 0,
		marginBottom: 0,
		textAlign: "center",
		fontSize: "34px",
		lineHeight: "1.22",
		fontWeight: tokens.fontWeightRegular,
		color: "var(--agent-chat-muted)",
		letterSpacing: "-0.01em",
		"@media (max-width: 900px)": {
			fontSize: "28px",
		},
		"@media (max-width: 640px)": {
			fontSize: "24px",
		},
	},
	welcomeHeadingStrong: {
		fontWeight: tokens.fontWeightSemibold,
		color: "var(--agent-chat-fg)",
		marginRight: "8px",
	},
	welcomeComposerContainer: {
		width: "100%",
		maxWidth: "980px",
		alignSelf: "center",
		display: "flex",
		flexDirection: "column",
		alignItems: "center",
		...shorthands.gap("18px"),
		...shorthands.padding("0", "12px", "24px"),
		boxSizing: "border-box",
	},
	promptFormDock: {
		width: "100%",
		maxWidth: "920px",
		alignSelf: "center",
		...shorthands.padding("0", "8px"),
		boxSizing: "border-box",
		display: "flex",
		justifyContent: "flex-start",
	},
	promptFormDockInner: {
		width: "40%",
		minWidth: "280px",
		maxWidth: "380px",
		"@media (max-width: 640px)": {
			width: "100%",
			minWidth: "0",
			maxWidth: "100%",
		},
	},
	suggestionsPanel: {
		...shorthands.border("1px", "solid", "var(--agent-chat-border)"),
		...shorthands.borderRadius("12px"),
		backgroundColor: "var(--agent-chat-surface)",
		boxShadow: tokens.shadow8,
		marginBottom: "10px",
		maxHeight: "230px",
		overflowY: "auto",
		overflowX: "hidden",
	},
	suggestionItem: {
		width: "100%",
		textAlign: "left",
		backgroundColor: "transparent",
		cursor: "pointer",
		...shorthands.border("none"),
		...shorthands.padding("12px", "16px"),
		...shorthands.borderBottom("1px", "solid", "var(--agent-chat-border)"),
		":last-child": {
			borderBottomStyle: "none",
		},
		":hover": {
			backgroundColor: "var(--agent-chat-hover)",
		},
	},
	suggestionTitle: {
		display: "block",
		fontSize: tokens.fontSizeBase400,
		fontWeight: tokens.fontWeightSemibold,
		color: "var(--agent-chat-fg)",
		lineHeight: tokens.lineHeightBase400,
	},
	suggestionDescription: {
		display: "block",
		marginTop: "4px",
		fontSize: tokens.fontSizeBase200,
		color: "var(--agent-chat-muted)",
		lineHeight: tokens.lineHeightBase200,
	},
	parameterPromptWrapper: {
		width: "100%",
		...shorthands.border("1px", "solid", "var(--agent-chat-brand)"),
		borderLeftWidth: "3px",
		borderLeftStyle: "solid",
		borderLeftColor: "var(--agent-chat-brand)",
		...shorthands.borderRadius("12px"),
		backgroundColor: "var(--agent-chat-surface)",
		...shorthands.padding("10px", "14px"),
		marginBottom: "10px",
		boxSizing: "border-box",
		":focus-within": {
			boxShadow: tokens.shadow4,
		},
	},
	parameterPromptTopRow: {
		display: "flex",
		alignItems: "center",
		justifyContent: "space-between",
		marginBottom: "8px",
	},
	parameterPromptTitle: {
		fontSize: tokens.fontSizeBase300,
		fontWeight: tokens.fontWeightSemibold,
		color: "var(--agent-chat-brand)",
	},
	parameterPromptDismissButton: {
		minWidth: "24px",
		width: "24px",
		height: "24px",
		...shorthands.border("none"),
		...shorthands.borderRadius("6px"),
		backgroundColor: "transparent",
		color: "var(--agent-chat-muted)",
		display: "inline-flex",
		alignItems: "center",
		justifyContent: "center",
		cursor: "pointer",
		":hover": {
			backgroundColor: "var(--agent-chat-hover)",
			color: "var(--agent-chat-fg)",
		},
	},
	parameterPromptFields: {
		display: "flex",
		flexDirection: "column",
		...shorthands.gap("8px"),
	},
	parameterPromptInputRow: {
		display: "flex",
		alignItems: "center",
		...shorthands.gap("8px"),
	},
	parameterPromptInput: {
		width: "100%",
		minHeight: "38px",
		...shorthands.border("1px", "solid", "var(--agent-chat-border)"),
		...shorthands.borderRadius("8px"),
		...shorthands.padding("8px", "12px"),
		backgroundColor: "var(--agent-chat-bg)",
		color: "var(--agent-chat-fg)",
		fontSize: tokens.fontSizeBase300,
		boxSizing: "border-box",
		outlineStyle: "none",
		":focus": {
			...shorthands.border("1px", "solid", "var(--agent-chat-brand)"),
		},
		"::placeholder": {
			color: "var(--agent-chat-muted)",
		},
	},
	parameterPromptSendSpacer: {
		minWidth: "36px",
		width: "36px",
		height: "36px",
		flexShrink: 0,
	},
	parameterPromptSendButton: {
		minWidth: "36px",
		width: "36px",
		height: "36px",
		...shorthands.border("none"),
		...shorthands.borderRadius("50%"),
		...shorthands.padding("0"),
		display: "inline-flex",
		alignItems: "center",
		justifyContent: "center",
		backgroundColor: "transparent",
		color: "var(--agent-chat-muted)",
		cursor: "pointer",
		flexShrink: 0,
		":disabled": {
			cursor: "not-allowed",
			opacity: 0.6,
		},
	},
	parameterPromptSendButtonActive: {
		backgroundColor: "var(--agent-chat-brand)",
		color: "#ffffff",
		":hover": {
			backgroundColor: "#0c5da5",
			color: "#ffffff",
		},
	},
	starterPrompts: {
		width: "100%",
		maxWidth: "860px",
		display: "flex",
		flexWrap: "wrap",
		justifyContent: "center",
		...shorthands.gap("8px"),
		...shorthands.padding("2px", "8px", "0"),
		boxSizing: "border-box",
	},
	starterPromptChip: {
		...shorthands.padding("9px", "14px"),
		...shorthands.border("1px", "solid", "var(--agent-chat-border)"),
		...shorthands.borderRadius("8px"),
		backgroundColor: "var(--agent-chat-card)",
		color: "var(--agent-chat-fg)",
		fontSize: tokens.fontSizeBase200,
		fontWeight: tokens.fontWeightMedium,
		cursor: "pointer",
		":hover": {
			backgroundColor: "var(--agent-chat-hover)",
		},
	},
	starterPromptMoreChip: {
		...shorthands.padding("9px", "14px"),
		...shorthands.border("1px", "solid", "var(--agent-chat-brand)"),
		...shorthands.borderRadius("8px"),
		backgroundColor: "var(--agent-chat-card)",
		color: "var(--agent-chat-brand)",
		fontSize: tokens.fontSizeBase200,
		fontWeight: tokens.fontWeightSemibold,
		cursor: "pointer",
		":hover": {
			backgroundColor: "var(--agent-chat-hover)",
		},
	},
	starterPromptMoreWrapper: {
		position: "relative" as const,
	},
	starterPromptOverflowDropdown: {
		position: "absolute" as const,
		top: "100%",
		left: "0",
		marginTop: "4px",
		backgroundColor: "var(--agent-chat-card)",
		...shorthands.border("1px", "solid", "var(--agent-chat-border)"),
		...shorthands.borderRadius("8px"),
		boxShadow: tokens.shadow8,
		zIndex: 10,
		minWidth: "160px",
		maxHeight: "220px",
		overflowY: "auto" as const,
		...shorthands.padding("4px", "0"),
	},
	starterPromptOverflowItem: {
		display: "block",
		width: "100%",
		textAlign: "left" as const,
		backgroundColor: "transparent",
		...shorthands.border("none"),
		...shorthands.padding("8px", "14px"),
		color: "var(--agent-chat-fg)",
		fontSize: tokens.fontSizeBase200,
		cursor: "pointer",
		whiteSpace: "nowrap" as const,
		":hover": {
			backgroundColor: "var(--agent-chat-hover)",
		},
	},
	starterPromptSkeletonContainer: {
		display: "flex",
		flexDirection: "column",
		alignItems: "center",
		rowGap: "8px",
		width: "100%",
		maxWidth: "860px",
		...shorthands.padding("2px", "8px", "0"),
		boxSizing: "border-box",
	},
	starterPromptSkeletonRow: {
		display: "flex",
		justifyContent: "center",
		columnGap: "8px",
		width: "100%",
		flexWrap: "nowrap" as const,
	},
	starterPromptShimmerChip: {
		height: "36px",
		...shorthands.borderRadius("8px"),
		backgroundColor: "#e8e8e8",
		backgroundImage:
			"linear-gradient(90deg, #e8e8e8 0%, #f5f5f5 40%, #e8e8e8 80%)",
		backgroundSize: "200% 100%",
		animationName: shimmer,
		animationDuration: "1.8s",
		animationTimingFunction: "linear",
		animationIterationCount: "infinite",
	},

	localConversationBody: {
		width: "100%",
		display: "flex",
		flexDirection: "column",
		...shorthands.gap("14px"),
		...shorthands.padding("8px", "8px", "0"),
		boxSizing: "border-box",
	},
	localAssistantBubble: {
		maxWidth: "78%",
		marginLeft: "32px",
		backgroundColor: "var(--agent-chat-surface)",
		color: "var(--agent-chat-fg)",
		...shorthands.border("1px", "solid", "var(--agent-chat-border)"),
		...shorthands.borderRadius("10px"),
		...shorthands.padding("10px", "14px"),
		fontSize: tokens.fontSizeBase200,
		lineHeight: tokens.lineHeightBase200,
	},
	typingIndicator: {
		display: "inline-flex",
		alignItems: "center",
		...shorthands.gap("6px"),
	},
	typingDot: {
		width: "6px",
		height: "6px",
		borderRadius: "50%",
		backgroundColor: "var(--agent-chat-brand)",
		animationName: typingBounce,
		animationDuration: "1.4s",
		animationTimingFunction: "ease-in-out",
		animationIterationCount: "infinite",
		animationFillMode: "both",
	},
	typingDot1: {
		animationDelay: "0s",
	},
	typingDot2: {
		animationDelay: "0.16s",
	},
	typingDot3: {
		animationDelay: "0.32s",
	},
	devModeLabel: {
		fontSize: tokens.fontSizeBase100,
		fontWeight: tokens.fontWeightSemibold,
		textTransform: "uppercase" as const,
		letterSpacing: "0.05em",
		color: "var(--agent-chat-muted)",
	},
	rawOutput: {
		margin: 0,
		whiteSpace: "pre-wrap" as const,
		wordBreak: "break-word" as const,
		fontFamily: tokens.fontFamilyMonospace,
		fontSize: tokens.fontSizeBase200,
		lineHeight: tokens.lineHeightBase200,
		color: "var(--agent-chat-fg)",
	},

	userBlock: {
		display: "flex",
		flexDirection: "column",
		alignItems: "flex-end",
		...shorthands.gap("4px"),
	},
	userTime: {
		fontSize: tokens.fontSizeBase100,
		color: "var(--agent-chat-muted)",
	},
	userBubble: {
		maxWidth: "86%",
		backgroundColor: "var(--agent-chat-brand)",
		color: "var(--agent-chat-user-fg)",
		...shorthands.padding("10px", "14px"),
		...shorthands.borderRadius("8px", "8px", "8px", "8px"),
		fontSize: tokens.fontSizeBase200,
		lineHeight: tokens.lineHeightBase200,
		fontWeight: tokens.fontWeightRegular,
	},

	assistantBlock: {
		display: "flex",
		flexDirection: "column",
		alignItems: "flex-start",
		...shorthands.gap("6px"),
	},
	assistantPreamble: {
		display: "flex",
		alignItems: "center",
		...shorthands.gap("8px"),
		color: "var(--agent-chat-muted)",
		fontSize: tokens.fontSizeBase100,
	},
	avatar: {
		width: "32px",
		height: "32px",
		borderRadius: "50%",
		display: "flex",
		alignItems: "center",
		justifyContent: "center",
		backgroundImage: "linear-gradient(135deg, #3367d6 0%, #5f4dd0 100%)",
		color: "#ffffff",
		flexShrink: 0,
	},
	assistantCard: {
		width: "100%",
		maxWidth: "980px",
		marginLeft: "32px",
		backgroundColor: "var(--agent-chat-card)",
		...shorthands.border("1px", "solid", "var(--agent-chat-border)"),
		...shorthands.borderRadius("10px"),
		...shorthands.padding("10px"),
		boxSizing: "border-box",
	},

	summaryCards: {
		display: "grid",
		gridTemplateColumns: "repeat(3, minmax(0, 1fr))",
		...shorthands.gap("10px"),
		marginBottom: "12px",
		"@media (max-width: 780px)": {
			gridTemplateColumns: "1fr",
		},
	},
	summaryCard: {
		display: "flex",
		alignItems: "center",
		...shorthands.gap("10px"),
		backgroundColor: "var(--agent-chat-card)",
		...shorthands.border("1px", "solid", "var(--agent-chat-border)"),
		borderLeftWidth: "3px",
		borderLeftStyle: "solid",
		...shorthands.borderRadius("8px"),
		...shorthands.padding("12px", "14px"),
	},
	summaryCardInfo: {
		borderLeftColor: "#0f6cbd",
	},
	summaryCardWarning: {
		borderLeftColor: "#d97706",
	},
	summaryCardSuccess: {
		borderLeftColor: "#2f9e44",
	},
	summaryIconWrap: {
		width: "28px",
		height: "28px",
		borderRadius: "50%",
		display: "flex",
		alignItems: "center",
		justifyContent: "center",
		color: "var(--agent-chat-muted)",
		backgroundColor: "var(--agent-chat-hover)",
		flexShrink: 0,
	},
	summaryText: {
		display: "flex",
		flexDirection: "column",
		minWidth: 0,
	},
	summaryValue: {
		fontSize: tokens.fontSizeHero700,
		lineHeight: "1.1",
		fontWeight: tokens.fontWeightSemibold,
	},
	summaryLabel: {
		fontSize: tokens.fontSizeBase200,
		color: "var(--agent-chat-muted)",
	},

	tableToolbar: {
		display: "flex",
		alignItems: "center",
		justifyContent: "space-between",
		...shorthands.gap("10px"),
		marginBottom: "8px",
		"@media (max-width: 760px)": {
			flexDirection: "column",
			alignItems: "stretch",
		},
	},
	showingText: {
		fontSize: tokens.fontSizeBase200,
		fontStyle: "italic",
		color: "var(--agent-chat-muted)",
	},
	searchBox: {
		display: "flex",
		alignItems: "center",
		...shorthands.gap("6px"),
		width: "250px",
		...shorthands.padding("2px", "8px"),
		...shorthands.border("1px", "solid", "var(--agent-chat-border)"),
		...shorthands.borderRadius("6px"),
		backgroundColor: "var(--agent-chat-surface)",
		"@media (max-width: 760px)": {
			width: "100%",
		},
	},
	searchIcon: {
		color: "var(--agent-chat-muted)",
		flexShrink: 0,
	},
	searchInput: {
		border: "none",
		outlineStyle: "none",
		backgroundColor: "transparent",
		color: "var(--agent-chat-fg)",
		width: "100%",
		fontSize: tokens.fontSizeBase200,
		"::placeholder": {
			color: "var(--agent-chat-muted)",
		},
	},

	tableWrapper: {
		overflowX: "auto",
		...shorthands.border("1px", "solid", "var(--agent-chat-border)"),
		...shorthands.borderRadius("8px"),
		backgroundColor: "var(--agent-chat-card)",
	},
	table: {
		width: "100%",
		minWidth: "860px",
		borderCollapse: "collapse",
		fontSize: tokens.fontSizeBase200,
	},
	th: {
		textAlign: "left",
		backgroundColor: "var(--agent-chat-hover)",
		...shorthands.padding("9px", "10px"),
		...shorthands.borderBottom("1px", "solid", "var(--agent-chat-border)"),
		color: "var(--agent-chat-muted)",
		fontWeight: tokens.fontWeightSemibold,
	},
	td: {
		...shorthands.padding("10px", "10px"),
		...shorthands.borderBottom("1px", "solid", "var(--agent-chat-border)"),
		color: "var(--agent-chat-fg)",
		verticalAlign: "middle",
	},
	requestLink: {
		color: "var(--agent-chat-brand)",
		textDecorationLine: "none",
		fontWeight: tokens.fontWeightMedium,
		":hover": {
			textDecorationLine: "underline",
		},
	},
	statusPill: {
		display: "inline-flex",
		alignItems: "center",
		...shorthands.gap("4px"),
		...shorthands.padding("3px", "10px"),
		...shorthands.borderRadius(tokens.borderRadiusCircular),
		...shorthands.border("1px", "solid", "var(--agent-chat-border)"),
		fontSize: tokens.fontSizeBase200,
		fontWeight: tokens.fontWeightSemibold,
		whiteSpace: "nowrap",
	},
	statusPillNeutral: {
		backgroundColor: "var(--agent-chat-hover)",
		color: "var(--agent-chat-muted)",
	},
	statusPillWarning: {
		backgroundColor: "#fff4eb",
		color: "#c2410c",
		...shorthands.border("1px", "solid", "#fdba74"),
	},

	actionRow: {
		display: "flex",
		alignItems: "center",
		...shorthands.gap("8px"),
		marginTop: "10px",
		flexWrap: "wrap",
	},
	actionButton: {
		...shorthands.padding("6px", "12px"),
		...shorthands.border("1px", "solid", "var(--agent-chat-border)"),
		...shorthands.borderRadius("6px"),
		backgroundColor: "var(--agent-chat-surface)",
		color: "var(--agent-chat-fg)",
		fontSize: tokens.fontSizeBase200,
		cursor: "pointer",
		":hover": {
			backgroundColor: "var(--agent-chat-hover)",
		},
	},

	detailsCard: {
		width: "100%",
		maxWidth: "980px",
		backgroundColor: "var(--agent-chat-card)",
		...shorthands.border("1px", "solid", "var(--agent-chat-border)"),
		...shorthands.borderRadius("8px"),
		...shorthands.padding("14px", "16px"),
		boxSizing: "border-box",
	},
	detailsHeader: {
		display: "flex",
		alignItems: "center",
		...shorthands.gap("8px"),
		marginBottom: "10px",
		flexWrap: "wrap",
	},
	detailsTitle: {
		fontSize: tokens.fontSizeHero700,
		fontWeight: tokens.fontWeightSemibold,
	},
	detailsRequestId: {
		fontFamily: tokens.fontFamilyMonospace,
		fontSize: tokens.fontSizeBase200,
		color: "var(--agent-chat-muted)",
	},
	detailsGrid: {
		...shorthands.borderTop("1px", "solid", "var(--agent-chat-border)"),
		paddingTop: "10px",
		display: "grid",
		gridTemplateColumns: "repeat(auto-fit, minmax(160px, 1fr))",
		...shorthands.gap("12px", "18px"),
	},
	detailItem: {
		display: "flex",
		flexDirection: "column",
		...shorthands.gap("2px"),
	},
	detailLabel: {
		fontSize: tokens.fontSizeBase100,
		textTransform: "uppercase",
		letterSpacing: "0.06em",
		color: "var(--agent-chat-muted)",
		fontWeight: tokens.fontWeightMedium,
	},
	detailValue: {
		fontSize: tokens.fontSizeBase300,
		fontWeight: tokens.fontWeightSemibold,
	},
	detailLink: {
		color: "var(--agent-chat-brand)",
		textDecorationLine: "none",
		":hover": {
			textDecorationLine: "underline",
		},
	},

	composerContainer: {
		width: "100%",
		maxWidth: "1024px",
		alignSelf: "center",
		...shorthands.padding("0", "18px", "14px"),
		boxSizing: "border-box",
		flexShrink: 0,
	},
	developerBadge: {
		display: "inline-flex",
		alignItems: "center",
		...shorthands.gap("6px"),
		...shorthands.padding("4px", "8px"),
		...shorthands.borderRadius("999px"),
		...shorthands.border("1px", "solid", "var(--agent-chat-border)"),
		backgroundColor: "var(--agent-chat-hover)",
		color: "var(--agent-chat-muted)",
		fontSize: tokens.fontSizeBase100,
		marginBottom: "6px",
	},
	composer: {
		display: "flex",
		flexDirection: "column",
		...shorthands.border("1px", "solid", "var(--agent-chat-border)"),
		...shorthands.borderRadius("14px"),
		backgroundColor: "var(--agent-chat-surface)",
		...shorthands.padding("8px", "6px", "4px", "8px"),
		boxShadow: tokens.shadow4,
	},
	composerInput: {
		width: "100%",
		border: "none",
		outlineStyle: "none",
		resize: "none" as const,
		backgroundColor: "transparent",
		color: "var(--agent-chat-fg)",
		fontFamily: tokens.fontFamilyBase,
		fontSize: tokens.fontSizeBase300,
		lineHeight: tokens.lineHeightBase300,
		minHeight: "28px",
		maxHeight: "120px",
		paddingRight: "4px",
		"::placeholder": {
			color: "var(--agent-chat-muted)",
		},
	},
	composerFooter: {
		display: "flex",
		alignItems: "center",
		justifyContent: "space-between",
		...shorthands.gap("8px"),
	},
	leftTools: {
		display: "flex",
		alignItems: "center",
		...shorthands.gap("4px"),
		minWidth: 0,
	},
	modelButton: {
		display: "inline-flex",
		alignItems: "center",
		...shorthands.gap("5px"),
		...shorthands.padding("2px", "8px"),
		...shorthands.borderRadius("10px"),
		color: "var(--agent-chat-muted)",
		fontSize: tokens.fontSizeBase200,
		backgroundColor: "transparent",
		...shorthands.border("none"),
		cursor: "pointer",
		":hover": {
			backgroundColor: "var(--agent-chat-hover)",
			color: "var(--agent-chat-fg)",
		},
	},
	modelSelector: {
		position: "relative",
		display: "inline-flex",
	},
	modelMenu: {
		position: "absolute",
		top: "calc(100% + 6px)",
		left: 0,
		minWidth: "220px",
		maxWidth: "280px",
		maxHeight: "280px",
		overflowY: "auto",
		backgroundColor: "var(--agent-chat-surface)",
		...shorthands.border("1px", "solid", "var(--agent-chat-border)"),
		...shorthands.borderRadius("10px"),
		boxShadow: tokens.shadow16,
		...shorthands.padding("4px"),
		zIndex: 25,
	},
	modelMenuOption: {
		width: "100%",
		display: "flex",
		alignItems: "center",
		justifyContent: "space-between",
		...shorthands.gap("12px"),
		...shorthands.padding("8px", "10px"),
		...shorthands.border("none"),
		...shorthands.borderRadius("8px"),
		backgroundColor: "transparent",
		color: "var(--agent-chat-fg)",
		cursor: "pointer",
		textAlign: "left",
		fontSize: tokens.fontSizeBase200,
		":hover": {
			backgroundColor: "var(--agent-chat-hover)",
		},
		":disabled": {
			opacity: 0.5,
			cursor: "not-allowed",
		},
	},
	modelMenuOptionActive: {
		backgroundColor: "var(--agent-chat-hover)",
	},
	modelIcon: {
		display: "inline-flex",
		alignItems: "center",
		justifyContent: "center",
	},
	modelMenuItemCheck: {
		color: "var(--agent-chat-brand)",
	},
	agentsBadge: {
		fontSize: tokens.fontSizeBase100,
		color: "var(--agent-chat-muted)",
		maxWidth: "180px",
		overflow: "hidden",
		textOverflow: "ellipsis",
		whiteSpace: "nowrap",
	},
	rightTools: {
		display: "flex",
		alignItems: "center",
		...shorthands.gap("2px"),
	},
	sendButton: {
		minWidth: "36px",
		width: "36px",
		height: "36px",
		...shorthands.borderRadius("50%"),
		...shorthands.padding("0"),
		color: "var(--agent-chat-muted)",
		":hover": {
			backgroundColor: "var(--agent-chat-hover)",
			color: "var(--agent-chat-muted)",
		},
	},
	sendButtonActive: {
		color: "#ffffff",
		backgroundColor: "var(--agent-chat-brand)",
		":hover": {
			backgroundColor: "#0c5da5",
			color: "#ffffff",
		},
	},
	messageItem: {},
	inProgressFooter: {
		...shorthands.padding("7px", "18px", "10px"),
	},
	footerSpacer: {
		height: "10px",
	},
});
